### ISSUE TITLE
4.15 broke our builds in TeamCity after successful build

### ISSUE THREAD

**Issue by bjartwolf** [fsharp/FAKE#1084]
Failed to resolve assembly: 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Not yet sure what causes this. The build log indicates that status is ok and then we get an exception

[09:42:51][Step 1/1] Status:                   Ok
[09:42:51][Step 1/1] ---------------------------------------------------------------------
[09:42:51][Step 1/1] 
[09:42:51][Step 1/1] Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[09:42:51][Step 1/1]    at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
[09:42:51][Step 1/1]    at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
[09:42:51][Step 1/1]    at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
[09:42:51][Step 1/1]    at Mono.Cecil.TypeReference.Resolve()
[09:42:51][Step 1/1]    at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
[09:42:51][Step 1/1]    at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
[09:42:51][Step 1/1]    at Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue(TypeReference type)
[09:42:51][Step 1/1]    at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
[09:42:51][Step 1/1]    at Mono.Cecil.SignatureReader.ReadCustomAttributeFixedArgument(TypeReference type)
[09:42:51][Step 1/1]    at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters)
[09:42:51][Step 1/1]    at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute)
[09:42:51][Step 1/1]    at Mono.Cecil.CustomAttribute.<Resolve>b__2(CustomAttribute attribute, MetadataReader reader)
[09:42:51][Step 1/1]    at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
[09:42:51][Step 1/1]    at Mono.Cecil.CustomAttribute.Resolve()
[09:42:51][Step 1/1]    at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
[09:42:51][Step 1/1]    at Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes(ICustomAttributeProvider provider)
[09:42:51][Step 1/1] -------------------
[09:42:51][Step 1/1]    at Mono.Cecil.ImmediateModuleReader.ReadProperties(TypeDefinition type)
[09:42:51][Step 1/1]    at Mono.Cecil.ImmediateModuleReader.ReadType(TypeDefinition type)
[09:42:51][Step 1/1]  FAKE usage
[09:42:51][Step 1/1]    at Mono.Cecil.ImmediateModuleReader.ReadTypes(Collection`1 types)
[09:42:51][Step 1/1] -------------------
[09:42:51][Step 1/1]    at Mono.Cecil.ImmediateModuleReader.ReadModule(ModuleDefinition module)
[09:42:51][Step 1/1]    at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
[09:42:51][Step 1/1]    at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
[09:42:51][Step 1/1]    at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
[09:42:51][Step 1/1]    at Fake.FSIHelper.runFAKEScriptWithFsiArgsAndRedirectMessages$cont@417-1(Boolean printDetails, CacheInfo cacheInfo, String wishName, DirectoryInfo cacheDir, StringBuilder fsiErrorOutput, IFsiSession session, Unit unitVar) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 438
[09:42:51][Step 1/1]    at Fake.FSIHelper.runFAKEScriptWithFsiArgsAndRedirectMessages$cont@367(Boolean printDetails, Boolean useCache, Boolean cleanCache, FsiOptions options, String scriptPath, CacheInfo cacheInfo, String wishName, TextWriter out, TextWriter err, Unit unitVar) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 417
[09:42:51][Step 1/1] Build failed.
[09:42:51][Step 1/1] Error:
[09:42:51][Step 1/1] Failed to resolve assembly: 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by bjartwolf** [comment]
https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L417

**Comment by forki** [comment]
Ok reverting this again.
Sorry. Fix under way

/cc @matthid

**Comment by bjartwolf** [comment]
Thanks for the quick response! We can test out pre-release versions or similar on a separate branch to verify in TeamCity for a future version if you like.

**Comment by forki** [comment]
Yes we will use prerelease for the next try

**Comment by forki** [comment]
Reverted version (4.15.1) should be available.

2016-01-19 9:53 GMT+01:00 Steffen Forkmann <sforkmann@gmail.com>:

> Yes we will use prerelease for the next try

**Comment by matthid** [comment]
Unfortunate that it fails on a fix which is only required for the test suite :(. Do we have a Mono.Cecil expert, because otherwise I could just disable this on release build?.

**Comment by forki** [comment]
that might be OK

**Comment by bjartwolf** [comment]
Works again in TeamCity on 4.15.1.
