### ISSUE TITLE
Cannot find FSI.exe

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FAKE#1092]
```
Running build failed.
Error:
System.Exception: Start of process fsi.exe failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@76-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.FSIHelper.executeFSIWithArgs(String workingDirectory, String script, FSharpList`1 extraFsiArgs, IEnumerable`1 args) in C:\code\fake\src\app\FakeLib\FSIHelper.fs:line 75
   at FSI_0001.Build.clo@199-18.Invoke(Unit _arg9) in d:\github\FSharp.Configuration\build.fsx:line 200
   at Fake.TargetHelper.runTarget@329(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 343
```
If I 

> fsi

than FSI starts normally.

**Comment by vasily-kirichenko** [comment]
On this line https://github.com/fsprojects/FSharp.Configuration/blob/master/build.fsx#L200

**Comment by forki** [comment]
we don't bundle fsi anymore. Is it installed? Can we find it in any of the paths listed under https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L14 ?

**Comment by matthid** [comment]
I would suggest calling FAKE instead of FSI for the documentation generation (ie changing the documentation generation to a FAKE script). This way you don't need fsi, FAKE will cache the script and you don't need defines for multiple documentation scenarios (just multiple FAKE tasks).

I did the change on projectscaffold some time ago here: https://github.com/fsprojects/ProjectScaffold/commit/6e4a6b63a8d6e63a1c89733bb69a2150ebf0deaf

**Comment by vasily-kirichenko** [comment]
Updated the script, everything works. Thanks!
