### ISSUE TITLE
Caching issue with 4.17 alpha5

### ISSUE THREAD

**Issue by CumpsD** [fsharp/FAKE#1106]
Repro:
Clone https://github.com/exira/user-ops/commit/7572e1c7d4df62db38eee92063b17da33c83a921
Run build.cmd twice

First time is fine, second time:
```
Checking Paket version (downloading latest stable)...
Paket.exe 2.47.1 is up to date.
Paket version 2.47.1.0
0 seconds - ready.
Octokit.fsx(3,1): warning FS0211: The search directory 'D:\Code\GH-Exira\user-ops\paket-files\fsharp\FAKE\modules\Octokit\../../../../../../packages/build/Octokit/lib/net45' could not be found
build.fsx(204,9): warning FS0044: This construct is deprecated. use SourceLink.Index
build.fsx(204,9): warning FS0044: This construct is deprecated. use SourceLink.Index
build.fsx(205,9): warning FS0044: This construct is deprecated. use SourceLink.Index
build.fsx(205,9): warning FS0044: This construct is deprecated. use SourceLink.Index
build.fsx(206,35): warning FS0044: This construct is deprecated. use .Commit instead
build.fsx(206,35): warning FS0044: This construct is deprecated. use .Commit instead
build.fsx(206,35): warning FS0044: This construct is deprecated. use .Commit instead

CACHING WARNING
this might happen after Updates...
please open a issue on FAKE and /cc @matthid ONLY IF this happens reproducibly)

Error: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Fake.FSIHelper.runScriptCached@309.Invoke(Unit unitVar0) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 311
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in C:\code\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1018
   at Fake.FSIHelper.runScriptCached(Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 309
   at Fake.FSIHelper.runFAKEScriptWithFsiArgsAndRedirectMessages(Boolean printDetails, FsiArgs _arg1, IEnumerable`1 env, FSharpFunc`2 onErrMsg, FSharpFunc`2 onOutMsg, Boolean useCache) in C:\code\FAKE\src\app\FakeLib\FSIHelper.fs:line 492
Unable to access D:\Code\GH-Exira\user-ops\.fake\build.fsx_ECE190EC.dll```
```
 /cc @matthid

**Comment by matthid** [comment]
Thanks will look into it! The build is still working as expected after this, correct?

**Comment by CumpsD** [comment]
Yes, it goes on, I assume you then fallback to non cache :)

The non alpha just blew up at that point.

**Comment by matthid** [comment]
I think this is https://github.com/fsharp/FAKE/pull/1104 and fixed with next version

**Comment by CumpsD** [comment]
I'll try again when there's an alpha 6 :)

**Comment by forki** [comment]
Alpha 7 is out. Please test

**Comment by CumpsD** [comment]
Working! :+1:
