### ISSUE TITLE
Fake.MSBuild tries to use mono to run MSBuild.exe

### ISSUE THREAD

**Issue by amazingant** [fsharp/FAKE#1202]
### Description

See the subject; FAKE is trying to use mono to run `MSBuild.exe` on my system. Seems to only happen on my Windows 10 system?

### Repro steps

1. Open powershell, navigate to a project directory

2. Run build script, watch it return an error

### Expected behavior

The build should run

### Actual behavior

The build stops with the following error message (file paths censored):

```
Running build failed.
Error:
System.Exception: Start of process mono failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@76-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.MSBuildHelper.build(FSharpFunc`2 setParams, String project) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 344
   at Fake.MSBuildHelper.MSBuildWithProjectProperties@389.Invoke(String project) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 389
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Fake.MSBuildHelper.MSBuildWithProjectProperties(String outputPath, String targets, FSharpFunc`2 properties, IEnumerable`1 projects) in C:\code\fake\src\app\FakeLib\MSBuildHelper.fs:line 389
   at FSI_0005.Global_build_script.clo@204-10.Invoke(String x) in <my build script here>:line 205
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at FSI_0005.Global_build_script.clo@201-8.Invoke(Unit _arg7) in <my build script here>:line 203
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 489
```

### Known workarounds

Running the same build script on a Windows 7 system appears to work fine.

### Related information 

* Windows 10
* Currently using FAKE 4.22.9, replacing it with 4.23.1 (current) doesn't change the behavior

I tried loading `FakeLib.dll` into the same powershell window I ran the build script from, but `[Fake.EnvironmentHelper]::isMono` returns `False`. Seems like everything that should be pointing me to mono is checking that flag correctly, so rather than providing a useful pull-request, I'm stuck putting up this issue report. :(

**Comment by forki** [comment]
Weird. Tbh I have no idea

**Comment by amazingant** [comment]
Gently poking around fake (took a moment to build, since the build script won't run :wink:)... it looks like it's doing this because I am running under Parallels, and the project is located on the Mac's primary drive.

I'm calling my `build.cmd` from `M:\Users\amazingant\GitHub\<ProjectName>\`, and `M:\` is the Mac's root partition. Seems that from there, [EnvironmentHelper.isMacOS](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/EnvironmentHelper.fs#L124) assumes that I'm on a Mac because `/usr/bin/osascript` exists under the `M:\` share. `isMacOS` changed in fake `4.11.0` which explains why I didn't used to run into this; I don't update fake very often :grimacing: 

I'm not sure if you have any bright ideas, but if you don't, I'll just keep in mind that this is broken for me. Seems like an odd edge-case for fake to handle.

**Comment by forki** [comment]
Can you detect that you are on Windows? Might override that setting.

**Comment by amazingant** [comment]
Sorry, just got back from lunch.

`Environment.OSVersion.Platform` returns `Win32NT`, and `Environment.CurrentDirectory` starts with the `<letter>:\` nomenclature? Checking either of those might work. Something like the following should handle #1019 still?

```FSharp
let isMacOS =
    (Environment.OSVersion.Platform = PlatformID.MacOSX) ||
    (Environment.OSVersion.Platform = PlatformID.Unix && (File.Exists "/usr/bin/osascript"))
```

**Comment by forki** [comment]
Yes isMac needs to be fixed

**Comment by amazingant** [comment]
Pull-request in, pending whatever tests I broke.

**Comment by amazingant** [comment]
Thanks, @forki :tada:
