### ISSUE TITLE
Default to NuGet.org in PublishUrl

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1241]
### Description

New versions of NuGet require source be specified, but FAKE's NuGetHelper does not provide a means of doing so.
### Repro steps

Using the latest NuGet client, attempt to publish a package.
### Expected behavior

The package is published.
### Actual behavior

NuGet spits out this error:

> Source parameter was not specified.
### Known workarounds

NuGet 3.4.4 [apparently fixes another regression](https://github.com/NuGet/Home/issues/2653) so that the config could be overridden. Without that, I don't know of any workarounds.
### Related information
- Windows 10
- .NET 4.6

**Comment by vasily-kirichenko** [comment]
I conform the bug:
```
Creating .nuspec file at D:\github\FSharp.Configuration\NuGet\FSharp.Configuration.0.6.0.nuspec
Created nuspec file D:\github\FSharp.Configuration\NuGet\FSharp.Configuration.0.6.0.nuspec
D:\github\FSharp.Configuration\packages\NuGet.Commandline\tools\nuget.exe pack -Version 0.6.0 -OutputDirectory "D:\github\FSharp.Configuration\nuget" "D:\github\FSharp.Configuration\NuGet\FSharp.Configuration.0.6.0.nuspec"
Deleting D:\github\FSharp.Configuration\NuGet\FSharp.Configuration.0.6.0.nuspec
D:\github\FSharp.Configuration\packages\NuGet.Commandline\tools\nuget.exe push "D:\github\FSharp.Configuration\nuget\FSharp.Configuration.0.6.0.nupkg" PRIVATEKEY  in WorkingDir: D:\github\FSharp.Configuration\NuGet Trials left: 5
Source parameter was not specified.
D:\github\FSharp.Configuration\packages\NuGet.Commandline\tools\nuget.exe push "D:\github\FSharp.Configuration\nuget\FSharp.Configuration.0.6.0.nupkg" PRIVATEKEY  in WorkingDir: D:\github\FSharp.Configuration\NuGet Trials left: 4
Source parameter was not specified.
D:\github\FSharp.Configuration\packages\NuGet.Commandline\tools\nuget.exe push "D:\github\FSharp.Configuration\nuget\FSharp.Configuration.0.6.0.nupkg" PRIVATEKEY  in WorkingDir: D:\github\FSharp.Configuration\NuGet Trials left: 3
Source parameter was not specified.
D:\github\FSharp.Configuration\packages\NuGet.Commandline\tools\nuget.exe push "D:\github\FSharp.Configuration\nuget\FSharp.Configuration.0.6.0.nupkg" PRIVATEKEY  in WorkingDir: D:\github\FSharp.Configuration\NuGet Trials left: 2
Source parameter was not specified.
D:\github\FSharp.Configuration\packages\NuGet.Commandline\tools\nuget.exe push "D:\github\FSharp.Configuration\nuget\FSharp.Configuration.0.6.0.nupkg" PRIVATEKEY  in WorkingDir: D:\github\FSharp.Configuration\NuGet Trials left: 1
Source parameter was not specified.
D:\github\FSharp.Configuration\packages\NuGet.Commandline\tools\nuget.exe push "D:\github\FSharp.Configuration\nuget\FSharp.Configuration.0.6.0.nupkg" PRIVATEKEY  in WorkingDir: D:\github\FSharp.Configuration\NuGet Trials left: 0
Source parameter was not specified.
Running build failed.
Error:
System.Exception: Error during NuGet push. D:\github\FSharp.Configuration\packages\NuGet.Commandline\tools\nuget.exe push "D:\github\FSharp.Configuration\nuget\FSharp.Configuration.0.6.0.nupkg" PRIVATEKEY
   at Fake.NuGetHelper.NuGet(FSharpFunc`2 setParams, String nuspecOrProjectFile) in C:\code\fake\src\app\FakeLib\NuGet\NugetHelper.fs:line 400
   at FSI_0005.Build.clo@168-13.Invoke(Unit _arg7)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492
```

**Comment by forki** [comment]
That's an issue in nuget, right? But can you send a pr that helps us?

**Comment by jochenwezel** [comment]
seems to be as being a blocking issue for next upcoming milestone release 3.5

**Comment by kentcb** [comment]
Nearly a year later and ran into this again. Had to roll back my NuGet client to 3.3.0.212 (a version I just happened to have lying around for another project).

**Comment by kentcb** [comment]
Well, I just started on a PR for this and found, to my surprise, that FAKE _does_ seemingly support this. However, the parameter name is `PublishUrl` (not `Source`) and it defaults to `null`.

Perhaps it should default to `https://www.nuget.org/api/v2/package`?

**Comment by matthid** [comment]
Yes the default should be changed. A PR would be welcome.

**Comment by matthid** [comment]
We got this now in https://www.nuget.org/packages/FAKE/4.61.2 thanks to @zvirja
