### ISSUE TITLE
[Cosmetic] When I by mistake #load the main script, it says something about a path being too long

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1263]
### Description

1.fsx

``` F#
#r @"packages\fake\tools\fakelib.dll"
open Fake

#load "1.fsx" // note that it loads itself.
              // this was a typo, I wanted to load 2.fsx


Target "T1" DoNothing

RunTargetOrDefault "T2"
```
### Expected behavior

FSI actually executes the script twice:
![image](https://cloud.githubusercontent.com/assets/4236651/15807359/ab1b4afc-2b5c-11e6-9b10-83d7c8b888f3.png)
The second run fails with a fake exception, if that hadn't happened, it would probably have executed forever (or until a stackoverflowexception)

Including yourself is probably always an error, so I don't really care about that, but it should atleast print a helpful error message.

I hit this by accident with a typo and searched for about an hour what was wrong with my script.
### Actual behavior

![image](https://cloud.githubusercontent.com/assets/4236651/15807345/0a641be8-2b5c-11e6-8680-700d12e3186c.png)

> Build failed.
> Error:
> The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
### Related information
- Operating system: Win10
- Version: 4.28.0
- .NET Runtime: latest Full .Net Framework, I think 4.6.1

**Comment by 0x53A** [comment]
I tested the FSI behaviour again:

```F#
#r @"packages\fake\tools\fakelib.dll"
open Fake

#load "1.fsx"

printfn "HELLO"
```

```
C:\Users\lr\Source\Repos\FakeCrashTest>"C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsi.exe" 1.fsx
HELLO
HELLO

C:\Users\lr\Source\Repos\FakeCrashTest>
```


There is also another difference between FSI and FAKE:

with these 4 scripts:

1.fsx

```F#

#load "2.fsx"
#load "3.fsx"

printfn "HELLO FROM 1"
```

2.fsx

```F#

#load "4.fsx"

printfn "HELLO FROM 2"
```

3.fsx

```F#

#load "4.fsx"

printfn "HELLO FROM 3"
```

4.fsx

```F#
printfn "HELLO FROM 4"
```


```

C:\Users\lr\Source\Repos\FakeCrashTest>"C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsi.exe" 1.fsx
HELLO FROM 4
HELLO FROM 2
HELLO FROM 4
HELLO FROM 3
HELLO FROM 1

C:\Users\lr\Source\Repos\FakeCrashTest>packages\fake\tools\fake.exe 1.fsx
HELLO FROM 2
HELLO FROM 4
HELLO FROM 3
HELLO FROM 1

C:\Users\lr\Source\Repos\FakeCrashTest>
```

**Comment by matthid** [comment]
Interesting, This looks like a FSharp.Compiler.Service bug. Nice find.
In fact: If you add a `type T = T` to `4.fsx` and change the printfn to ```printfn "%A" ``4``.T``` it will crash.

```
$ /c/Program\ Files\ \(x86\)/Microsoft\ SDKs/F#/4.0/Framework/v4.0/Fsi.exe 1.fsx
HELLO FROM 4
HELLO FROM 2 T
HELLO FROM 4
HELLO FROM 3 T
HELLO FROM 1


$ /c/PROJ/Yaaf.AdvancedBuilding/packages/FAKE/tools/FAKE.exe 1.fsx
FsiEvaluationException:

Error:

        2.fsx(3,27): error FS0039: The namespace or module '4' is not defined


Output: [Loading C:\Test\2.fsx
         Loading C:\Test\4.fsx
         Loading C:\Test\3.fsx
         Loading C:\Test\1.fsx]


Input: C:\Test\1.fsx

Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System.Exception: Operation failed. The error text has been print the error stream. To return the corresponding FSharpErrorInfo use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.EvalScript(String filePath)
   at Yaaf.FSharp.Scripting.Helper.evalScript@1097.Invoke(String arg00) in C:\code\fake\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1097
   at Yaaf.FSharp.Scripting.Helper.save_@1072-2.Invoke(Unit unitVar0) in C:\code\fake\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1073
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in C:\code\fake\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1018
   at Yaaf.FSharp.Scripting.Helper.redirectOut@1044[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err, FSharpFunc`2 f) in C:\code\fake\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1051
   at Yaaf.FSharp.Scripting.Helper.save_@1071-1.Invoke(String text) in C:\code\fake\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1072
   --- End of inner exception stack trace ---
   at Yaaf.FSharp.Scripting.Helper.save_@1071-1.Invoke(String text) in C:\code\fake\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1080
   at Yaaf.FSharp.Scripting.Helper.session@1100.Yaaf-FSharp-Scripting-IFsiSession-EvalScriptWithOutput(String ) in C:\code\fake\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1102
   at Fake.FSIHelper.runScriptUncached(Boolean useCache, String scriptPath, IEnumerable`1 fsiOptions, Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in C:\code\fake\src\app\FakeLib\FSIHelper.fs:line 468
2.fsx(3,27): error FS0039: The namespace or module '4' is not defined
```

I might send a test case to FSharp.Compiler.Service and then eventually try to fix it. But this might take a good while :). (Really) quickly looking at the source it seems like they revert the order somewhere and then maybe call distinct on the reverted list? Need to test if this happens on the latest `visualfsharp` code as well, then it might be a regression.

/cc @dsyme

**Comment by matthid** [comment]
I think this has since been fixed up-stream.
