### ISSUE TITLE
Creating DB with FAKE fails using SQL Server 2016

### ISSUE THREAD

**Issue by hanskhe** [fsharp/FAKE#1376]
### Description

Attempting to create a database in SQL Server using FAKE.

### Repro steps

1. Running Fake.SQL.SqlServer.getServerInfo using the following code

```
Target "CreateDb" (fun _ ->
    let serverInfo = getServerInfo getConnectionString
    let serverName = getDatabaseNamesFromServer serverInfo |> Seq.head
    if not (existDBOnServer serverInfo serverName)
        then serverInfo |> CreateDb |> ignore
)
```

### Expected behavior

Database is created.

### Actual behavior

Program crashes, giving the following stack trace:

 1) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.SqlServer.SqlClrProvider, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.SqlServer.SqlClrProvider, Version=10.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'
   at Microsoft.SqlServer.Management.Common.ConnectionManager.CallerHavePermissionToUseSQLCLR()
   at Microsoft.SqlServer.Management.Common.ConnectionManager..ctor()
   at Microsoft.SqlServer.Management.Common.ServerConnection..ctor()
   at Fake.SQL.SqlServer.getServerInfo(String connectionString) in C:\code\fake\src\app\Fake.SQL\SQLServer.fs:line 18      at FSI_0005.Build.clo@237-39.Invoke(Unit _arg17)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 492

### Known workarounds

Installing SQL Server 2012

### Related information 

* Windows 10.
* Branch: Master
* .NET 4.6.1
* SQL Server 2016

@freein and @hanskhe

**Comment by freein** [comment]
I have provided #1377
