### ISSUE TITLE
Build fails on "SourceLink" target

### ISSUE THREAD

**Issue by TeaDrivenDev** [fsharp/FAKE#1638]
### Description

I cannot build FAKE, because the `SourceLink` target fails due to the project format of `Fake.Core.BuildServer` not being recognized.

### Repro steps

1. Build FAKE using `./build.cmd CreateNuGet SkipTests`

### Expected behavior

The build succeeds.

### Actual behavior

The build fails with

```
Starting Target: SourceLink (==> DotnetCoreCreateZipPackages)
source indexing D:\Development\OpenSource\FAKE\build\FAKE.pdb
Running build failed.
Error:
System.Exception: unable to load proj file `D:\Development\OpenSource\FAKE\src\app\Fake.Core.BuildServer\Fake.Core.BuildServer.fsproj` with properties: [("Configuration", "Release")], error The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  D:\Development\OpenSource\FAKE\src\app\Fake.Core.BuildServer\Fake.Core.BuildServer.fsproj
   at SourceLink.VsBuild.Project-Load-Static@22.Invoke(String message) in C:\projects\sourcelink\SourceLink\VsProj.fs:line 22
   at SourceLink.VsBuild.Project.Load.Static(String proj, IEnumerable`1 globalProps) in C:\projects\sourcelink\SourceLink\VsProj.fs:line 22
   at SourceLink.VsBuild.Project.LoadRelease.Static(String proj) in C:\projects\sourcelink\SourceLink\VsProj.fs:line 23
   at FSI_0005.Build.clo@500-30.Invoke(String f)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at FSI_0005.Build.clo@497-29.Invoke(Unit _arg11)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\proj\FAKE\src\app\FakeLib\TargetHelper.fs:line 682
``` 

### Known workarounds

None.

### Related information

* Window 10 Pro
* `master` branch
* Visual Studio 15.3.2, .NET 4.7, .NET Core SDK 2.0.0

I suppose I might be missing some other part of that cursed `dotnet` black magic toolchain, but I'm completely out of my depth here and have no idea what's going on.

**Comment by matthid** [comment]
Yes I got the same. I decided to disable the SourceLink-Target for now. Hopefully we get that back up and running with new SDK...
