### ISSUE TITLE
fake.exe crashes when Target scans long paths

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FAKE#167]
I think we should switch Scan to win32 functions which can deal with long paths. 

Call stack:

Unhandled Exception: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 ch
aracters, and the directory name must be less than 248 characters.
   at System.IO.Path.SafeSetStackPointerValue(Char\* buffer, Int32 index, Char value)
   at System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
   at System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean check
ForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.IO.FileSystemInfo.get_FullName()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.scanDirectory@302.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 304
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Fake.FileSetHelper.Files@325.GenerateNext(IEnumerable`1& next) in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FakeLib\FileSet.fs:line 332
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at <StartupCode$FAKE>.$Program.main@() in D:\BuildAgent-03\work\7c94b030153a768a\src\app\FAKE\Program.fs:line 29

**Comment by petersondrew** [comment]
Perhaps we should add some default excludes to some of the built-in functions that perform globbing? Or allow the user to supply some? I've had to sprinkle this bit any time I do any globbing for files in my scripts to prevent this error:
```fsharp
let projects = !!"src/**/*.??proj" -- "./**/node_modules/*" -- "./**/bower_components/*"
```

**Comment by hiscodeness** [comment]
@petersondrew Does that really work for you? Even with the excludes added, I still get the ```PathTooLongException``` when enumerating the results.

**Comment by petersondrew** [comment]
Perhaps something is overriding your excludes? That pattern fixed the issue for us.

-----Original Message-----

**Comment by hiscodeness** [comment]
Thanks for verifying. Unfortunately, excludes didn't help us. To fix this problem I had to avoid using `**` pattern in my inclusion selectors. That is, I must write
```
let assemblyInfos = !! "./src/*/Properties/AssemblyInfo.cs"
let unitTests = !! "src/*/bin/*/*.Tests.dll"
let nuspecs = !! "src/*/*.nuspec"
```
This works for now as the directory structure is consistent with regards to these path depths. I'd really like a more robust solution, though.

**Comment by forki** [comment]
@colinbul can we try to just ignore the long paths (avoid the error)?

**Comment by colinbull** [comment]
Yep, this should be simple enough, however on top of simply ignoring we should also emit a warning telling the user exactly which paths have been ignored. Unfortunately I have negative time at the minute :-1: so wont get round to this for a bit.

**Comment by lucax88x** [comment]
still having this problem.. please skip the error and add the warning!
