### ISSUE TITLE
[FAKE5] Paket Code doesn't work first time 

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1672]
Looks a bit like restore is too late?
Works second time.
```
 - Microsoft.NETCore.Platforms 2.0.0
 - Microsoft.NETCore.Targets 2.0.0
 - FSharp.NET.Sdk 1.0.5
 - Microsoft.Win32.Registry 4.4.0
 - System.Security.AccessControl 4.4.0
 - System.Security.Principal.Windows 4.4.0
Locked version resolution written to C:\proj\Protobuf_1\.fake\build.fsx\paket.lock
Build failed.
Error:
System.Exception: Folder C:\Users\matthid\.nuget\packages\System.Runtime.WindowsRuntime\4.3.0 doesn't exist. Did you restore groups Main?
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at <StartupCode$Paket-Core>.$DependencyCache.exprs@199-2.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](AsyncImplResult`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronouslyInCurrentThread[a](CancellationToken token, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at Paket.DependencyCache.SetupGroup(GroupName groupName)
   at Paket.DependencyCache.OrderedGroups(GroupName groupName)
   at Paket.LoadingScripts.ScriptGeneration.cachedGroups@184-1.Invoke(GroupName g)
   at Microsoft.FSharp.Collections.IEnumerator.map@114.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.IEnumerator.map@114.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.LoadingScripts.ScriptGeneration.generateScriptContent(PaketContext _arg1)
   at Paket.LoadingScripts.ScriptGeneration.scriptData@315-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.LoadingScripts.ScriptGeneration.scriptData@313.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Paket.LoadingScripts.ScriptGeneration.constructScriptsFromData(DependencyCache depCache, FSharpList`1 groups, FSharpList`1 providedFrameworks, FSharpList`1 providedScriptTypes)
   at Paket.UpdateProcess.SmartInstall(DependenciesFile dependenciesFile, UpdateMode updateMode, UpdaterOptions options)
   at Paket.UpdateProcess.UpdateGroup(String dependenciesFileName, GroupName groupName, UpdaterOptions options)
   at <StartupCode$Paket-Core>.$PublicAPI.UpdateGroup@247-3.Invoke(Unit unitVar0)
   at Paket.Utils.RunInLockedAccessMode[a](String rootFolder, FSharpFunc`2 action)
   at Paket.Dependencies.UpdateGroup(String groupName, Boolean force, Boolean withBindingRedirects, Boolean cleanBindingRedirects, Boolean createNewBindingFiles, Boolean installAfter, SemVerUpdateMode semVerUpdateMode, Boolean touchAffectedRefs)
   at Fake.Runtime.FakeRuntime.restoreOrUpdate@102(Boolean printDetails, String cacheDir, Dependencies paketDependencies, String groupStr, GroupName groupName, FrameworkIdentifier framework, FileInfo lockFilePath, Unit unitVar0)
   at Fake.Runtime.FakeRuntime.paketCachingProvider(Boolean printDetails, String cacheDir, Dependencies paketDependencies, FSharpOption`1 group)
   at Fake.Runtime.FakeRuntime.prepareFakeScript(Boolean printDetails, String script)
   at Fake.Runtime.FakeRuntime.prepareAndRunScriptRedirect(Boolean printDetails, FSharpList`1 fsiOptions, String scriptPath, IEnumerable`1 envVars, FSharpFunc`2 onErrMsg, FSharpFunc`2 onOutMsg, Boolean useCache)
   at Fake.Runtime.FakeRuntime.prepareAndRunScript(Boolean printDetails, FSharpList`1 fsiOptions, String scriptPath, IEnumerable`1 envVars, Boolean useCache)
   at Program.handleCli@75.Invoke(ParseResults`1 runArgs) in C:\Proj\FAKE\src\app\Fake.netcore\Program.fs:line 148
```

**Comment by matthid** [comment]
Closing this as we have a workaround in FAKE in place and issue is open in Paket (https://github.com/fsprojects/Paket/issues/2785)
