### ISSUE TITLE
[FAKE5] Exception when omitting target on fake call in beta 2

### ISSUE THREAD

**Issue by putschoeglwe** [fsharp/FAKE#1687]
### Description

Call of Default Target raises exception:

`build\packages\FAKE\tools\fake build\build.fsx`

`System.InvalidOperationException: Invalid Fake Execution context was found: Expected 'Fake.Core.Context+RuntimeContextWrapper' but was 'Fake.Core.Context+RuntimeContextWrapper'
   at Fake.Core.Context.forceFakeContext()
   at Fake.Core.Context.getFakeVar[a](String name)
   at Fake.Core.Context.fakeVar@120.Invoke(Unit unitVar0)
   at Fake.Core.Target.addTargetWithDependencies(FSharpList`1 dependencies, FSharpFunc`2 body, String name)
   at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@() in C:\projects\src\TatFakeLib\trunk\build\build.fsx:line 41
Stopped due to error`

### Expected behavior

build of default target specified in `Target.RunOrDefault "CI"` <-- my default target in build.fsx

### Known workarounds

Do not rely on default target but provide the target explicitely:

`build\packages\FAKE\tools\fake build\build.fsx CI`

### Related information 

* Win 10
* FAKE 5.0.0-beta002
* .net46

### Full stacktrace:
`Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System.Exception: Operation failed. The error text has been printed in the error stream. To return the corresponding FSharpErrorInfo use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2593
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.EvalScript(String filePath) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2760
   at Yaaf.FSharp.Scripting.Helper.evalScript@1325.Invoke(String arg00) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1325
   at Yaaf.FSharp.Scripting.Helper.save_@1298-2.Invoke(Unit unitVar0) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1299
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1243
   at Yaaf.FSharp.Scripting.Helper.redirectOut@1269[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err, FSharpFunc`2 f) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1276
   at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1298
   --- End of inner exception stack trace ---
   at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1306
   at Yaaf.FSharp.Scripting.Helper.session@1328.Yaaf-FSharp-Scripting-IFsiSession-EvalScriptWithOutput(String ) in C:\proj\FAKE\src\app\FakeLib\unknown:line 1
   at Fake.FSIHelper.runScriptUncached(Boolean useCache, IEnumerable`1 fsiOptions, Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in C:\proj\FAKE\src\app\FakeLib\FSIHelper.fs:line 534
System.InvalidOperationException: Invalid Fake Execution context was found: Expected 'Fake.Core.Context+RuntimeContextWrapper' but was 'Fake.Core.Context+RuntimeContextWrapper'
   at Fake.Core.Context.forceFakeContext()
   at Fake.Core.Context.getFakeVar[a](String name)
   at Fake.Core.Context.fakeVar@120.Invoke(Unit unitVar0)
   at Fake.Core.Target.addTargetWithDependencies(FSharpList`1 dependencies, FSharpFunc`2 body, String name)
   at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@() in C:\projects\src\TatFakeLib\trunk\build\build.fsx:line 41
Stopped due to error`

**Comment by putschoeglwe** [comment]
workaround not working any more in beta 3 release :-(

**Comment by matthid** [comment]
@putschoeglwe Can you verify that it still doesn't work without cache (or when you delete the `.fake` folder).
A repro would be nice as it seems to work on the FAKE repository itself

If the types don't match that means that somewhere multiple `FakeLib.dll` files are loaded. Now we need to figure out how that happens...

**Comment by putschoeglwe** [comment]
yes i tried that- run multiple tests- also on beta 3 where the issue arises even if i pass a target.

in my setup i have a build extension hat builds on FakeLib. I use paket to manage all my build dependencies such as FAKE, NUnit, xUnit and my Lib (that references FakeLib Nuget). My build script uses the FAKE Lib provided by the NuGet.

But as i recall both have been updated to beta 3 and i thought there should be no issue there?

What i want is to have full dependency management on my builds (I will look into merging some extensions into FAKE with my manager, but some are pretty specialised stuff) and therefore want to manage libs and tools by paket.

Might there be a problem where FAKE.exe and the build script have to reference the same dll?

**Comment by matthid** [comment]
Yes, can you create a repro sample for how you are using FAKE, such that I can take a look at how we might be able to fix that?

**Comment by putschoeglwe** [comment]
I can confirm that the problem was caused by the build script referencing a different FakeLib.dll than the executing FAKE.exe.

I thought I had an elegant solution to manage all build dependencies with paket and use paket to generate include scripts that I wanted to use in my build.fsx:

paket.dependencies:
```
framework: >= net46

generate_load_scripts: true

source https://www.nuget.org/api/v2
source http://mynugetfeed/nugets/nuget

nuget Fake >= 5.0.0 prerelease  
nuget MyBuildLib >= 4.9 publish  //<- this assembly uses FakeLib NuGet and caused the problem!
nuget xunit.runner.console
nuget NuGet.CommandLine
nuget NUnit
```
calling `paket install` from the command line would result in the deployment of all required infrastructure for a build.

the build.fsx would look something like this:
```
#load @".paket\load\net46\MyBuildLib.fsx"


open Fake.Core.TargetOperators
open Fake.EnvironmentHelper
open Fake.Core
open Fake.Core.Globbing.Operators
...
```

My problem is now, that I have to manually edit the load scripts generated by paket. MyBuildLib references several other NuGets and I did not want to include them in the NuGet but use NuGet dependencies.
In addition to MyBuildLib I wanted to use the same mechanism to manage all my dependent tools such as FAKE, xUnit, NUnit,...

Any idea for an elegant solution?

As a side note/question: any suggestion where to discuss such topics?

**Comment by matthid** [comment]
> Any idea for an elegant solution

Well, maybe the fault is not on you side. Maybe I need to loosen the requirements/dependencies a bit. The problem is that this might create other problems... I don't see a easy way to overwrite the fakelib reference from the face core itself.
Did you try referencing the bundled fakelib.dll explicitly before loading your package depending on fakelib?

> where to discuss such topics

Github is fine, but Gitter or Slack works as well (just mention me otherwise I might miss it)

**Comment by matthid** [comment]
Tbh. maybe you should consider to look at the new fake 5 runner as well

**Comment by matthid** [comment]
Also using the legacy/obsolete apis should work as well.

(I'm not saying that I don't want to fix it. I think this is quite important to fix but I have no idea how that could work technically...)

**Comment by matthid** [comment]
So I guess you found an acceptable solution/workaround?

**Comment by putschoeglwe** [comment]
I reference the dll from FAKE by hand. 
I remove the reference to FakeLib from MyLib NuGet and add it ahead of loading MyLib in my buildscript.
not as elegant as could be but sufficiently so :)
```
#r @"packages/FAKE/tools/FakeLib.dll"
#load @".paket/load/net46/MyLib.fsx"


open Fake.EnvironmentHelper
open Fake.Core
```

I will try to put together a sample build script as we need some documentation where we could discuss how things should be done.

The purpose is that I want to model my infrastructure as code- all the tools and libs and other requirements I need to run my build- in later stages even with docker images?
Perhaps an idea for paket?

**Comment by matthid** [comment]
Problem is that you always need something for bootstrapping. The question is just with what you want to start.
