### ISSUE TITLE
Can no longer build FAKE

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1698]
### Description

Up until my last PR, I could build FAKE locally and now I can't. I get a whole bunch of errors like this:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	Fake.Core.IntegrationTests	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1122	
```
I'm using VS2017 and I've just installed the 4.6.1 targetting pack without any change in outcome.

### Repro steps

1. Grab FAKE code.
2. Build in VS2017.

### Expected behavior

It builds.

### Actual behavior

It doesn't build per the above error message.

### Related information 

* Windows 10
* `master`
* VS2017

**Comment by kentcb** [comment]
I don't seem to be able to edit the description, so adding a comment for clarity. I've tried installing:

* [4.6.1 Developer Pack](https://www.microsoft.com/en-au/download/details.aspx?id=49978)
* [4.6 Targetting Pack](https://www.microsoft.com/en-us/download/details.aspx?id=48136)

Neither has helped.

**Comment by dsyme** [comment]
> I don't seem to be able to edit the description

Something odd has happened to github, it's not allowing editing of any comments or descriptions

**Comment by kentcb** [comment]
Also I thought maybe I could build via `build.cmd` as a worst-case scenario, but I'm getting:
```
>  .\build.cmd
Paket version 5.101.0
Last restore is still up to date.
Performance:
 - Runtime: 1 second
FsiEvaluationException:

Error:

        build.fsx(902,9): error FS0039: The value, namespace, type or module 'GitHub' is not defined. Maybe you want one of the following:
           Git



Output: [Loading C:\Users\Kent\Repository\FAKE\build.fsx]


Input: C:\Users\Kent\Repository\FAKE\build.fsx
\Arguments:
  C:\fsi.exe

Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System.Exception: Operation failed. The error text has been printed in the error stream. To return the corresponding FSharpErrorInfo use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2593
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.EvalScript(String filePath) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2760
   at Yaaf.FSharp.Scripting.Helper.evalScript@1325.Invoke(String arg00) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1325
   at Yaaf.FSharp.Scripting.Helper.save_@1298-2.Invoke(Unit unitVar0) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1299
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1243
   at Yaaf.FSharp.Scripting.Helper.redirectOut@1269[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err, FSharpFunc`2 f) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1276
   at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1298
   --- End of inner exception stack trace ---
   at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1306
   at Yaaf.FSharp.Scripting.Helper.session@1328.Yaaf-FSharp-Scripting-IFsiSession-EvalScriptWithOutput(String ) in C:\proj\FAKE\src\app\FakeLib\unknown:line 1
   at Fake.FSIHelper.runScriptUncached(Boolean useCache, IEnumerable`1 fsiOptions, Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in C:\proj\FAKE\src\app\FakeLib\FSIHelper.fs:line 534
build.fsx(902,9): error FS0039: The value, namespace, type or module 'GitHub' is not defined. Maybe you want one of the following:
   Git
```

**Comment by kentcb** [comment]
I forgot to mention also that I installed VS 15.3.5 over the weekend. I've noticed that F# syntax highlighting is no longer working as well - not sure if that's just because of the above problem though.

**Comment by kentcb** [comment]
Oh ffs, I just went ahead and installed _all_ targeting packs via the VS installer and now everything has righted itself. Guess it's a misleading error message from the build system then....
