### ISSUE TITLE
build.fsx GitHub.createClientWithToken broken on clean clone

### ISSUE THREAD

**Issue by bentayloruk** [fsharp/FAKE#1711]
### Description

* git clone FAKE into fresh directory.
* Run `build.cmd`
* Build fails with `build.fsx(902,9): error FS0039: The value, namespace, type or module 'GitHub' is not defined.`

<details>
<summary>Full build.cmd output</summary>

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\@build\FAKE.clean>build.cmd
Paket version 5.101.0
Last restore is still up to date.
Performance:
 - Runtime: 2 seconds
build.fsx(902,9): error FS0039: The value, namespace, type or module 'GitHub' is not defined. Maybe you want one of the following:
   Git

CACHING WARNING
this might happen after Updates...
please open a issue on FAKE and /cc @matthid ONLY IF this happens reproducibly)

Error: System.Exception: We could not find a type similar to '<StartupCode$FSI_0001>.$FSI_0001_Build$fsx' containing a 'main@' method in the cached assembly (C:\@build\FAKE.clean/.fake/build.fsx_C576906F.dll)!
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1243
   at Fake.FSIHelper.runScriptCached(Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in C:\proj\FAKE\src\app\FakeLib\FSIHelper.fs:line 329
   at Fake.FSIHelper.runFAKEScriptWithFsiArgsAndRedirectMessages(Boolean printDetails, FsiArgs _arg1, IEnumerable`1 env, FSharpFunc`2 onErrMsg, FSharpFunc`2 onOutMsg, Boolean useCache) in C:\proj\FAKE\src\app\FakeLib\FSIHelper.fs:line 598
Unable to access C:\@build\FAKE.clean\.fake\build.fsx_C576906F.dll
FsiEvaluationException:

Error:

        build.fsx(902,9): error FS0039: The value, namespace, type or module 'GitHub' is not defined. Maybe you want one of the following:
           Git



Output: [Loading C:\@build\FAKE.clean\build.fsx]


Input: C:\@build\FAKE.clean\build.fsx
\Arguments:
  C:\fsi.exe

Exception: Yaaf.FSharp.Scripting.FsiEvaluationException: Error while compiling or executing fsharp snippet. ---> System.Exception: Operation failed. The error text has been printed in the error stream. To return the corresponding FSharpErrorInfo use the EvalInteractionNonThrowing, EvalScriptNonThrowing or EvalExpressionNonThrowing
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.commitResult[a,b](FSharpChoice`2 res) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2593
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.EvalScript(String filePath) in C:\GitHub\dsyme\FSharp.Compiler.Service\src\fsharp\fsi\fsi.fs:line 2760
   at Yaaf.FSharp.Scripting.Helper.evalScript@1325.Invoke(String arg00) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1325
   at Yaaf.FSharp.Scripting.Helper.save_@1298-2.Invoke(Unit unitVar0) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1299
   at Yaaf.FSharp.Scripting.Helper.consoleCapture[a](TextWriter out, TextWriter err, FSharpFunc`2 f) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1243
   at Yaaf.FSharp.Scripting.Helper.redirectOut@1269[a](Boolean preventStdOut, OutStreamHelper out, OutStreamHelper err, FSharpFunc`2 f) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1276
   at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1298
   --- End of inner exception stack trace ---
   at Yaaf.FSharp.Scripting.Helper.save_@1297-1.Invoke(String text) in C:\proj\FAKE\paket-files\matthid\Yaaf.FSharp.Scripting\src\source\Yaaf.FSharp.Scripting\YaafFSharpScripting.fs:line 1306
   at Yaaf.FSharp.Scripting.Helper.session@1328.Yaaf-FSharp-Scripting-IFsiSession-EvalScriptWithOutput(String ) in C:\proj\FAKE\src\app\FakeLib\unknown:line 1
   at Fake.FSIHelper.runScriptUncached(Boolean useCache, IEnumerable`1 fsiOptions, Boolean printDetails, CacheInfo cacheInfo, TextWriter out, TextWriter err) in C:\proj\FAKE\src\app\FakeLib\FSIHelper.fs:line 534
build.fsx(902,9): error FS0039: The value, namespace, type or module 'GitHub' is not defined. Maybe you want one of the following:
   Git


C:\@build\FAKE.clean>
```

</details>

### Repro steps

As per the description.

### Expected behavior

Builds OK.

### Actual behavior

Build fails with error in description details above.

### Known workarounds

Comment out lines using GitHub module.

### Initial investigation
 
It seems to me that the broken GitHub module reference is due to the module not being present in the `FakeLib.dll` that the Paket restore pulls in.  Looking at that assembly (version 5.0.0-beta004) with ILSpy, I can see a Slack module in the `Fake.Api` namespace, but no GitHub module.  If I look at build.fsx in VS it shows the Fake.Api open statement in grey, thinking it is unused, because there is no GitHub module present.

### Related information

* Operating system - Windows Server 2012.
* Branch - Master.

**Comment by matthid** [comment]
Yes a `paket update` is needed but while doing that another issue poped up (see https://github.com/fsharp/FAKE/pull/1697). For now you can still build by using fake 5 from chocolatey and by building via `fake run build.fsx` (or by updating fake nuget package via paket). Your workaround is fine as well, sorry for the inconvenience...

**Comment by bentayloruk** [comment]
Thanks for the explanation.  I'll have another crack later.

**Comment by matthid** [comment]
Can you retry and tell me if it still doesn't work?
