### ISSUE TITLE
Build Failing (dotnet pack)

### ISSUE THREAD

**Issue by auxym** [fsharp/FAKE#1749]
### Description

I can't seem to build FAKE using the default build script (dotnet core build).

### Repro steps

1. Clone FAKE master branch (642a01a as of writing this)

2. Run build.cmd

### Expected behavior

Successful build

### Actual behavior

```
Finished Target: DotnetPackage_
Running build failed.
Error:
System.Exception: dotnet pack failed with code 1
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
   at Fake.DotNet.Cli.DotnetPack(FSharpFunc`2 setParams, String project) in C:\proj\FAKE\src\app\Fake.DotNet.Cli\Dotnet.fs:line 533
   at FSI_0005.Build.clo@679-44.Invoke(TargetParameter _arg1)
   at Fake.Core.Target.runSingleTarget(Target target) in C:\proj\FAKE\src\app\Fake.Core.Target\Target.fs:line 449

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                        Duration
------                        --------
Clean                         00:00:01.1194343
StartDnc                      00:00:00.0000368
InstallDotnetCore             00:00:01.4578201
DownloadPaket                 00:00:01.4242200
RenameFSharpCompilerService   00:00:13.4892270
SetAssemblyInfo               00:00:04.9306793
Total:                        00:03:24.7259226
Status:                       Failure
---------------------------------------------------------------------
  1) dotnet pack failed with code 1
---------------------------------------------------------------------
```

Looking a bit higher up the logs, I find that every single assembly that is build outputs a message like this:

```
<...>AppData\Local\microsoft\dotnet\sdk\2.0.3\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(204,5): error : The file '<...>\FAKE\src\app\Fake.Core.Tasks\bin\Release\net46\Fake.Core.Tasks.pdb' to be packed was not found on disk. [<...>\FAKE\src\app\Fake.Core.Tasks\Fake.Core.Tasks.fsproj]
```
### Known workarounds

None I could figure out.

### Related information 

* Win10
* Branch: master
* dotnet CLI 2.0.3

**Comment by matthid** [comment]
Yes I think we currently need Visual Studio installed otherwise stuff will not work

**Comment by matthid** [comment]
Ok after updating the dotnet-cli I saw the same issue. So it seems to have been introduced when using the newer 2.0.3 instead of 2.0.0. I came up with https://github.com/fsharp/FAKE/pull/1763/commits/a84cf4da7e67545a948326d872fad51493384c77 and I'm trying to get everything working again on latest.

**Comment by matthid** [comment]
Thanks for reporting!
