### ISSUE TITLE
rc001 System.InvalidOperationException

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/FAKE#1853]
### Description

throws on first target in script, this problem started with rc001

````
System.InvalidOperationException: Invalid Fake Execution context was found: Expected 'Fake.Core.Context+RuntimeContextWrapper' but was 'Fake.Core.Context+RuntimeContextWrapper'
           at Fake.Core.Context.forceFakeContext() in C:\proj\FAKE\src\app\Fake.Core.Context\Context.fs:line 109
           at Fake.Core.Context.getFakeVar[a](String name) in C:\proj\FAKE\src\app\Fake.Core.Context\Context.fs:line 118
           at Fake.Core.Context.fakeVar@131.Invoke(Unit unitVar0) in C:\proj\FAKE\src\app\Fake.Core.Context\Context.fs:line 131
           at Fake.Core.TargetModule.addTargetWithDependencies(FSharpList`1 dependencies, FSharpFunc`2 body, String name) in C:\proj\FAKE\src\app\Fake.Core.Target\Target.fs:line 280
           at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@() in E:\GitRepos\FsRegEx\build.fsx:line 91
        Stopped due to error
````

Nothing substantial changed since more successful builds with beta27

**Comment by matthid** [comment]
This might happen if you mix fakelib with the new packages. I don’t think we should support this. Please either use fakelib or the new packages. Or if that is not the case please show how to reproduce this

**Comment by jackfoxy** [comment]
> This might happen if you mix fakelib with the new packages

This was apparently the cause. Now completely off of legacy FAKE, and this is no longer a problem.
