### ISSUE TITLE
Could not load file or assembly 'Fake.Core.String, Version=5.0.0.0

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/FAKE#1859]
### Description

````
Fake.Core.BuildFailedException: Target 'CopyBinaries' failed. ---> System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Fake.Core.String, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
           at Fake.IO.Shell.CopyDir@145.Invoke(String file)
           at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
           at Fake.IO.Shell.CopyDir(String target, String source, FSharpFunc`2 filterFile)
           at FSI_0005.Build.clo@120-3.Invoke(Tuple`2 tupledArg) in E:\GitRepos\FsRegEx\build.fsx:line 120
           at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
           at FSI_0005.Build.clo@116-2.Invoke(TargetParameter _arg3) in E:\GitRepos\FsRegEx\build.fsx:line 120
           at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in C:\proj\FAKE\src\app\Fake.Core.Target\Target.fs:line 163
           --- End of inner exception stack trace ---
           --- End of inner exception stack trace ---
           at Fake.Core.TargetModule.runInternal(Boolean singleTarget, Int32 parallelJobs, String targetName, FSharpList`1 args) in C:\proj\FAKE\src\app\Fake.Core.Target\Target.fs:line 533
           at Fake.Core.TargetModule.runOrDefault@618.Invoke(Boolean singleTarget, Int32 parallelJobs, FSharpList`1 arguments) in C:\proj\FAKE\src\app\Fake.Core.Target\Target.fs:line 619
           at Fake.Core.TargetModule.runWithDefault$cont@580(FSharpFunc`2 fDefault, FSharpMap`2 results, Unit unitVar) in C:\proj\FAKE\src\app\Fake.Core.Target\Target.fs:line 607
           at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@() in E:\GitRepos\FsRegEx\build.fsx:line 383
        Stopped due to error
````

### Repro steps

````
open Fake.Core
open Fake.Core.TargetOperators
open Fake.DotNet
open Fake.IO
open Fake.IO.FileSystemOperators
open Fake.IO.Globbing.Operators
open Fake.Tools.Git
open Fake.Testing.Expecto
open System
open System.IO

Target.create "CopyBinaries" (fun _ ->
    !! "src/**/*.??proj"
    -- "src/**/*.shproj"
    |>  Seq.map (fun f -> ((Path.getDirectory f) </> "bin" </> configuration, "bin" </> (Path.GetFileNameWithoutExtension f)))
    |>  Seq.iter (fun (fromDir, toDir) -> Shell.CopyDir toDir fromDir (fun _ -> true))
)
````

### Expected behavior

copy binaries

### Actual behavior

throws

### Related information 

* FAKE 5.0 rc001

**Comment by matthid** [comment]
can you post you build.fsx.lock file and verbose log (fake -v build)?

**Comment by matthid** [comment]
This is because you should not match new packages with the old runner ... I guess you manually added packages via `#r` and missed some dependencies there?

**Comment by jackfoxy** [comment]
I would have thought this is the new runner, in ````build.cmd````
````packages\FAKE.Core\tools\FAKE.exe build.fsx````
