### ISSUE TITLE
Fake 5.6 cache failure

### ISSUE THREAD

**Issue by SteveGilham** [fsharp/FAKE#2083]
### Description

On second and subsequent builds after clearing the `.fake` folders from the project
```
Retrieving assembly list from cache failed, please report a bug: System.Exception: Cache is invalid as 'Microsoft.Win32.Primitives, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' doesn't exist
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at Fake.Runtime.FakeRuntime.readFromCache@393-1.Invoke(String line) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 401
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fake.Runtime.FakeRuntime.getKnownAssemblies@420(FakeConfig config, String cacheDir, Lazy`1 paketDependenciesFile, VerboseLevel logLevel, GroupName groupName, FrameworkIdentifier framework, FileInfo lockFilePath, String assemblyCacheHashFile, String assemblyCacheFile, Lazy`1 lockFile, Lazy`1 cache, Lazy`1 writeIntellisenseTask, Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 427
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Update build script to refer to Fake 5.6 -- simple repro sample here 

[setup-test.fsx.txt](https://github.com/fsharp/FAKE/files/2364192/setup-test.fsx.txt)

2. Run it twice

### Expected behavior

It just works

### Actual behavior

Cache failure message as above, then it just works

### Known workarounds

Delete the .fake folder(s) and try again

### Related information 

* Operating system -- Win X Home
* Branch -- Nuget package 5.6.0
* .NET Runtime, CoreCLR or Mono Version -- .net core Version: 2.1.3-servicing-26724-03
* Indications of severity -- severe enough that you tell me to report it
* Version of FAKE (4.X, 5.X) -- 5.6.0
* (if performance issue) Performance information, links to performance testing scripts -- N/A

**Comment by matthid** [comment]
Thanks a lot for reporting I think I found the issue

**Comment by matthid** [comment]
Also I unlisted the 5.6 runner packages (chocolatey, dotnet-fake and fake-cli)

**Comment by matthid** [comment]
[5.6.1](https://github.com/fsharp/FAKE/releases/tag/5.6.1) is released and should work

**Comment by BlythMeister** [comment]
@matthid i'm using 5.6.1 and have the same error on a fresh machine.

```
Retrieving assembly list from cache failed, please report a bug: System.Exception: Cache is invalid as 'Microsoft.Win32.Primitives, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' doesn't exist
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at Fake.Runtime.FakeRuntime.readFromCache@393-1.Invoke(String line) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 401
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fake.Runtime.FakeRuntime.getKnownAssemblies@420(FakeConfig config, String cacheDir, Lazy`1 paketDependenciesFile, VerboseLevel logLevel, GroupName groupName, FrameworkIdentifier framework, FileInfo lockFilePath, String assemblyCacheHashFile, String assemblyCacheFile, Lazy`1 lockFile, Lazy`1 cache, Lazy`1 writeIntellisenseTask, Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 427
```

**Comment by matthid** [comment]
@BlythMeister Please give more context and steps to reproduce ;)

**Comment by BlythMeister** [comment]
i deleted the .nuget folder on my machine (for another reason)
next time i ran fake, i got this error.
ran it again...all ok...

**Comment by matthid** [comment]
Yes then the cache was invalid and the detection was ok ;)

**Comment by BlythMeister** [comment]
hmmm...big red stacktrace may not be required for an "expected exception" ;)

**Comment by matthid** [comment]
I feel like that is acceptable for people messing around with the cache folder by hand ;)

**Comment by BlythMeister** [comment]
this also happened on a brand new machine, fresh checkout of repo and run...because the cache doesn't exist before the 1st load :D

**Comment by matthid** [comment]
but then you commited the .fake directory which you shouldn't?
