### ISSUE TITLE
NuGet.Version.getLastNuGetVersion fails to parse response

### ISSUE THREAD

**Issue by TangoMikeOscar** [fsharp/FAKE#2124]
### Description

NuGet.Version.getLastNuGetVersion fails to parse the response when using a myget feed.

### Repro steps

Call NuGet.Version.getLastNuGetVersion with a package on a myget feed

### Expected behavior

Call should return the SemVerInfo of the latest version of the package

### Actual behavior

The call causes an error:

```
-> BuildFailedException: Target 'PushPackages' failed.
   StackTrace:
        at Fake.Core.TargetModule.runInternal(Boolean singleTarget, Int32 parallelJobs, String targetName, FSharpList`1 args) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 654
        at Fake.Core.TargetModule.runOrDefaultWithArguments@840.Invoke(Boolean singleTarget, Int32 parallelJobs, FSharpList`1 arguments) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 841
        at Fake.Core.TargetModule.runWithDefault$cont@795-1(Boolean allowArgs, FSharpFunc`2 fDefault, FSharpMap`2 results, Unit unitVar) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 827
        at <StartupCode$Build_DEB2AE5EDD32A4D859D2F0179426F1C047BBF8A3AD6B26CA8391A476A1C5DFBF>.$Build$fsx.main@() in D:\<snip>\build\Build.fsx:line 194
-> One or more errors occurred. (Data at the root level is invalid. Line 1, position 1.)
-> XmlException: Data at the root level is invalid. Line 1, position 1.
   StackTrace:
        at System.Xml.XmlTextReaderImpl.Throw(Exception e)
        at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
        at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
        at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
        at System.Xml.XmlTextReaderImpl.Read()
        at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
        at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
        at Fake.DotNet.NuGet.Version.getLastNuGetVersion(String server, String packageName) in D:\a\1\s\src\app\Fake.DotNet.NuGet\NuGetVersion.fs:line 68
        at Build.clo@137-26.Invoke(Unit unitVar) in D:\<snip>\build\Build.fsx:line 143
        at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
        at Build.clo@119-21.Invoke(TargetParameter _arg9) in D:\<snip>\build\Build.fsx:line 131
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 196
```

It would seem that it is trying to parse the response as xml where myget is returning json (I have verified this with fiddler). It seems that myget is returning the `Content-Type` header as `application/json;odata=verbose;charset=utf-8` where the code looks to be checking for exactly `application/json` (https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.DotNet.NuGet/NuGetVersion.fs#L59 line 59) since this doesn't match it assumes it's xml.

### Known workarounds

None that I know of. I am migrating from Fake v4 so this is blocking my script from working.

### Related information 

* Operating system
Windows 10
* Branch
Stable
* .NET Runtime, CoreCLR or Mono Version
DotNetCore 2.1.402
* Version of FAKE (4.X, 5.X)
5.7.2 of Fake.DotNet.NuGet module

**Comment by matthid** [comment]
So do I understand it correctly that this worked in fake 4 and is no longer working?

**Comment by TangoMikeOscar** [comment]
Our previous implementation was using the deprecated exe runner in the FAKE package version 5.3 and using the deprecated targets and modules.

If you want more specific details I can provide them. But yes, with this method it was working.

**Comment by TangoMikeOscar** [comment]
I will try and do that over the next few days and let you know.

**Comment by TangoMikeOscar** [comment]
Hi, just to quick update on this. I have copied the getLastNuGetVersion function into my script and added the following lines:

```
let text, headers = client.DownloadStringAndHeaders url
let hasContentType = headers.ContainsKey "Content-Type"

headers |> Seq.iter (fun x -> 
    printfn "Header - \"%s\" = \"%s\"" x.Key (System.String.Join(";", x.Value))
)
printfn "hasContentType %b" hasContentType
```

The output I get is:
```
Header - "Cache-Control" = "no-cache"
Header - "Content-Security-Policy" = "frame-ancestors 'none'"
Header - "DataServiceVersion" = "2.0;"
Header - "Date" = "Thu, 25 Oct 2018 12:32:15 GMT"
Header - "Referrer-Policy" = "strict-origin-when-cross-origin"
Header - "Request-Context" = "appId=cid-v1:3583f036-7c37-44b3-bda0-ae457a178111"
Header - "X-Content-Type-Options" = "nosniff;nosniff"
Header - "X-Frame-Options" = "deny"
Header - "X-XSS-Protection" = "1; mode=block"
hasContentType false
```

That is obviously indicating the `Content-Type` header is not present in the list that the function `DownloadStringAndHeaders` returns. Fiddler is showing the header is definitely returned so it would seem the problem is in that function. 

I will try and dig further.

**Comment by TangoMikeOscar** [comment]
So it looks like the **Dotnet standard** HttpClient is causing this problem, I have called the same url using the HttpClient in a bit of C# code and `Content-Type` is not in the `response.Headers` collection.

However I have found it in the `response.Content.Headers` collection so it looks like these 2 header collections just need to be concatenated in the `DownloadStringAndHeaders` function.

**Comment by TangoMikeOscar** [comment]
I've added pull request #2170 that fixes the issue.
