### ISSUE TITLE
Concurrent problems with Shell.Exec

### ISSUE THREAD

**Issue by lukapor** [fsharp/FAKE#2214]
### Description

When I run buildscripts i got concurreny problem
For this time I have only stack trace, which can help

System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
      at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
      at System.Collections.Generic.HashSet`1.Add(T item)
      at Fake.Core.Process.doWithProcessList[a](FSharpFunc`2 f) in D:\a\1\s\src\app\Fake.Core.Process\Process.fs:line 309
      at Fake.Core.Process.rawStartProcess(Process proc) in D:\a\1\s\src\app\Fake.Core.Process\Process.fs:line 402
      at Fake.Core.Process.asyncShellExec@823-2.Invoke(Process _arg1) in D:\a\1\s\src\app\Fake.Core.Process\Process.fs:line 828
      at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
      at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)
      at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   --- End of stack trace from previous location where exception was thrown ---
      at Microsoft.FSharp.Control.AsyncResult`1.Commit()
      at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
      at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
      at Loop.Build.Globals.exec(String cmd, String workDir, FSharpList`1 args) in /home/jenkins/workspace/4O_Backend/src/build-configuration.fsx:line 237
      at Loop.Build.Prepare.RunElevated@106.Invoke(String sql) in /home/jenkins/workspace/4O_Backend/src/build-prepare.fsx:line 118)

I run this with parralel options so more Shell.Exec was started parralel

### Related information 

* Operating system
* Branch
* CoreCLR
* Portable fake 5.10.1
* both win and linux env

**Comment by matthid** [comment]
Indeed, thanks for the report!
