### ISSUE TITLE
Production release failed

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#2265]
### Description

https://dev.azure.com/fakebuild/FSProjects/_releaseProgress?_a=release-environment-logs&releaseId=349&environmentId=739

```
2019-02-26T16:26:21.1965222Z > "C:\ProgramData\chocolatey\bin\choco.exe" push "./release\dotnetcore\chocolatey/fake.5.12.2.nupkg" --source https://push.chocolatey.org/ --apikey *** -y  (In: false, Out: false, Err: false)
2019-02-26T16:26:23.9651361Z Chocolatey v0.10.11
2019-02-26T16:28:00.8752029Z Attempting to push fake.5.12.2.nupkg to https://push.chocolatey.org/
2019-02-26T16:29:42.7377305Z Failed to process request. 'Origin Time-out'. 
2019-02-26T16:29:42.7378329Z The remote server returned an error: (524) Origin Time-out..
2019-02-26T16:29:42.8006053Z 
2019-02-26T16:29:42.8010981Z 
2019-02-26T16:29:42.8145811Z 
2019-02-26T16:29:42.8147541Z ---------------------------------------------------------------------
2019-02-26T16:29:42.8147740Z Build Time Report
2019-02-26T16:29:42.8148357Z ---------------------------------------------------------------------
2019-02-26T16:29:42.8175123Z Target                            Duration
2019-02-26T16:29:42.8175331Z ------                            --------
2019-02-26T16:29:42.8224619Z PrepareArtifacts                  00:00:10.6053199
2019-02-26T16:29:42.8251509Z 
2019-02-26T16:29:42.8324401Z ##[error]DotNetCorePushChocolateyPackage   00:03:21.7937758   (choco failed with exit code 1.)
2019-02-26T16:29:42.8335506Z 
2019-02-26T16:29:42.8336112Z ##[warning]ReleaseDocs                       00:00:00           (skipped)
2019-02-26T16:29:42.8336730Z 
2019-02-26T16:29:42.8337043Z ##[warning]DotNetCorePushNuGet               00:00:00           (skipped)
2019-02-26T16:29:42.8337267Z 
2019-02-26T16:29:42.8337560Z ##[warning]FastRelease                       00:00:00           (skipped)
2019-02-26T16:29:42.8337838Z Total:                            00:03:32.5594283
2019-02-26T16:29:42.8337916Z 
2019-02-26T16:29:42.8338188Z ##[error]Status:                           Failure
2019-02-26T16:29:42.8338474Z ---------------------------------------------------------------------
2019-02-26T16:29:42.8511749Z Script reported an error:
2019-02-26T16:29:42.8589790Z -> BuildFailedException: Target 'DotNetCorePushChocolateyPackage' failed.
2019-02-26T16:29:42.9482451Z    StackTrace:
2019-02-26T16:29:42.9492230Z         at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 820
2019-02-26T16:29:42.9492798Z         at Fake.Core.TargetModule.runOrDefault(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 936
2019-02-26T16:29:42.9493023Z         at <StartupCode$build_1C14B92CA097B2971C1FB7B6B5EF065172A25D3AFB98D4DCEE38EA431DF1F7C4>.$Build$fsx.main@() in D:\a\r1\a\FAKE\build.fsx:line 1334
2019-02-26T16:29:42.9493314Z -> One or more errors occurred. (choco failed with exit code 1.)
2019-02-26T16:29:42.9493692Z -> choco failed with exit code 1.
2019-02-26T16:29:42.9516354Z    StackTrace:
2019-02-26T16:29:42.9516814Z         at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
2019-02-26T16:29:42.9517599Z         at Fake.Windows.Choco.callChoco(String exePath, String args, TimeSpan timeout) in D:\a\1\s\src\app\Fake.Windows.Chocolatey\Chocolatey.fs:line 369
2019-02-26T16:29:42.9517981Z         at Fake.Windows.Choco.push(FSharpFunc`2 setParams, String nupkgPath) in D:\a\1\s\src\app\Fake.Windows.Chocolatey\Chocolatey.fs:line 834
2019-02-26T16:29:42.9518322Z         at Build.clo@884-64.Invoke(TargetParameter _arg2) in D:\a\r1\a\FAKE\build.fsx:line 894
2019-02-26T16:29:42.9518639Z         at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 201
```

We might want to introduce some retry-logic or at least allow to start the release again (and include checks if stuff already exists)

Currently we cannot "redeploy" existing artifacts as it will always fail with "existing package / conflict" error

**Comment by matthid** [comment]
This maybe is something we want to have "built-in" into our tasks? Maybe enable it with a flag?
