### ISSUE TITLE
Xamarin Android x86_64 build fails

### ISSUE THREAD

**Issue by iXamDev** [fsharp/FAKE#2313]
### Description

I try to build multiple APKs Xamarin.Android project with FAKE. The output should be a separate APKs for each ABI. Everything works except _AndroidAbiTarget.X86And64_ configuration. 

### Repro steps

1. Build Android for AndroidAbiTarget.X86And64

### Expected behavior

APK builded

### Actual behavior

Build fails with MSBuild error

> MakeBundleNativeCodeExternal: /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2873,3): error : Sequence contains no matching element

`Script reported an error:
-> BuildFailedException: Target 'Build-MultiApks' failed.
   StackTrace:
        at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 820
        at Fake.Core.TargetModule.runOrDefault(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 968
        at <StartupCode$build_temp_9768A34E6D40DD91047B0C51436770AA3E89B56876469E188395AE0F782EA83D>.$build_temp$fsx.main@() in /Users/ivan/Projects/Emp/build/FAKE/build_temp.fsx:line 468
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
   StackTrace:
        at Fake.DotNet.MSBuild.handleAfterRun(String command, FSharpOption`1 binLogPath, Int32 exitCode, String project) in D:\a\1\s\src\app\Fake.DotNet.MSBuild\MSBuild.fs:line 756
        at Fake.DotNet.MSBuild.build(FSharpFunc`2 setParams, String project) in D:\a\1\s\src\app\Fake.DotNet.MSBuild\MSBuild.fs:line 849
        at Fake.DotNet.Xamarin.buildPackages@258(AndroidPackageParams param, FSharpOption`1 abi, FSharpOption`1 manifestFile) in D:\a\1\s\src\app\Fake.DotNet.Xamarin\Xamarin.fs:line 275
        at Fake.DotNet.Xamarin.buildSpecificApk@298(AndroidPackageParams param, String manifestFile, String name, FSharpFunc`2 transformVersion, AndroidAbiTarget target) in D:\a\1\s\src\app\Fake.DotNet.Xamarin\Xamarin.fs:line 307
        at Fake.DotNet.Xamarin.createTargetPackage@319(AndroidPackageParams param, String manifestFile, AndroidAbiTarget target, FSharpFunc`2 transformVersion) in D:\a\1\s\src\app\Fake.DotNet.Xamarin\Xamarin.fs:line 320
        at Fake.DotNet.Xamarin.createPackageAbiSpecificApk@331-1.GenerateNext(IEnumerable`1& next) in D:\a\1\s\src\app\Fake.DotNet.Xamarin\Xamarin.fs:line 332
        at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
        at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
        at build_temp.PackageMultiAbiAndroid(String projectPath, String config) in /Users/ivan/Projects/Emp/build/FAKE/build_temp.fsx:line 278
        at build_temp.clo@422-8.Invoke(TargetParameter _arg5) in /Users/ivan/Projects/Emp/build/FAKE/build_temp.fsx:line 424
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 201
`

### Known workarounds

I believe that problem in https://github.com/fsharp/FAKE/blob/master/src/app/Fake.DotNet.Xamarin/Xamarin.fs#L311
Wrong configuration name: it should be **x**86_64, not X86_64

You may check it [here](https://docs.microsoft.com/ru-ru/xamarin/android/deploy-test/building-apps/build-process)

I checked it using MSBuild directly from command line
`/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild project.csproj /t:PackageForAndroid /p:RestorePackages=False /p:AndroidSupportedAbis=X86_64 /p:OutputPath=/Users/android/ /p:Configuration=Release` - **fails**

and
`/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild project.csproj /t:PackageForAndroid /p:RestorePackages=False /p:AndroidSupportedAbis=x86_64 /p:OutputPath=/Users/android/ /p:Configuration=Release` - **work as expected**

### Related information 

* MacOS 10.14.4
* Version of F# Make (5.12.6)
* Paket.Core: 5.198.0
* MSBuild Build Engine version 16.0.42-preview+g804bde742b for Mono

**Comment by matthid** [comment]
Thanks a lot for the report and the analysis
