### ISSUE TITLE
Using NuGet.feedUrl fails

### ISSUE THREAD

**Issue by bchavez** [fsharp/FAKE#2323]
Calling:
```fsharp
let pkg = NuGet.getLatestPackage NuGet.feedUrl "Bogus"
```

The `NuGet.feedUrl` is defined as:

https://github.com/fsharp/FAKE/blob/300fe0bacca25298e939a3897ba85f93162dcaaa/src/app/Fake.DotNet.NuGet/NuGet.fs#L629

Produces the following exception:
```csharp
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
info       00:00:01.5417436   ('=' is an unexpected token. The expected token is ';'. Line 45, position 288.)
Total:     00:00:01.6602855
Status:    Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'info' failed.
   StackTrace:
        at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 820
        at Fake.Core.TargetModule.runOrDefault(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 968
        at <StartupCode$build_15E56598F9F60270360A111C870EAE2DE760A83DEF77ECACF0EF3F88BE0C0A13>.$Build$fsx.main@() in C:\Code\Projects\Public\Bogus\Builder\build.fsx:line 40
-> One or more errors occurred. ('=' is an unexpected token. The expected token is ';'. Line 45, position 288.)
-> XmlException: '=' is an unexpected token. The expected token is ';'. Line 45, position 288.
   StackTrace:
        at System.Xml.XmlTextReaderImpl.Throw(Exception e)
        at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
        at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
        at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
        at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
        at System.Xml.XmlTextReaderImpl.ParseAttributes()
        at System.Xml.XmlTextReaderImpl.ParseElement()
        at System.Xml.XmlTextReaderImpl.ParseElementContent()
        at System.Xml.XmlTextReaderImpl.Read()
        at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
        at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
        at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
        at System.Xml.XmlDocument.Load(XmlReader reader)
        at System.Xml.XmlDocument.LoadXml(String xml)
        at Fake.Core.Xml.createDoc(String text) in D:\a\1\s\src\app\Fake.Core.Xml\Xml.fs:line 113
        at Fake.DotNet.NuGet.NuGet.getFeedPackagesFromUrl(String url) in D:\a\1\s\src\app\Fake.DotNet.NuGet\NuGet.fs:line 781
        at Fake.DotNet.NuGet.NuGet.getLatestPackage(String repoUrl, String packageName) in D:\a\1\s\src\app\Fake.DotNet.NuGet\NuGet.fs:line 787
        at Utils.GetLatestNugetPackageVersion(String packageName) in C:\Code\Projects\Public\Bogus\Builder\Utils.fsx:line 31
        at Build.clo@191-7.Invoke(TargetParameter _arg4) in C:\Code\Projects\Public\Bogus\Builder\build.fsx:line 193
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 201
```
https://github.com/fsharp/FAKE/blob/300fe0bacca25298e939a3897ba85f93162dcaaa/src/app/Fake.DotNet.NuGet/NuGet.fs#L786-L789

https://github.com/fsharp/FAKE/blob/300fe0bacca25298e939a3897ba85f93162dcaaa/src/app/Fake.DotNet.NuGet/NuGet.fs#L780-L783

Let's find out why. The URL that gets built by FAKE:
```
http://go.microsoft.com/fwlink/?LinkID=206669/Packages()?$filter=(Id%20eq%20'Bogus')%20and%20IsLatestVersion
```
Executing:
```
bchavez@linux:~$ http 'http://go.microsoft.com/fwlink/?LinkID=206669/Packages()?$filter=(Id%20eq%20'Bogus')%20and%20IsLatestVersion'
GET /fwlink/?LinkID=206669/Packages()?$filter=(Id%20eq%20Bogus)%20and%20IsLatestVersion HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, compress
Host: go.microsoft.com
User-Agent: HTTPie/0.5.0


HTTP/1.1 302 Moved Temporarily
Cache-Control: max-age=0, no-cache, no-store
Connection: keep-alive
Content-Length: 0
Date: Tue, 28 May 2019 19:13:49 GMT
Expires: Tue, 28 May 2019 19:13:49 GMT
Location: https://www.microsoft.com
Pragma: no-cache
Request-Context: appId=cid-v1:7d63747b-487e-492a-872d-762362f77974
Server: Kestrel
X-Powered-By: ASP.NET
X-Response-Cache-Status: True
```

The `302` redirect is to `Location: https://www.microsoft.com` which is Microsoft's homepage website. Trying to parse Microsoft's homepage for the `Bogus` NuGet package probably won't work. :cry: 

However, `http://go.microsoft.com/fwlink/?LinkID=206669` without ***any*** URL parameters, produces the correct redirect:
```
bchavez@linux:~$ http 'http://go.microsoft.com/fwlink/?LinkID=206669'
GET /fwlink/?LinkID=206669 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, compress
Host: go.microsoft.com
User-Agent: HTTPie/0.5.0


HTTP/1.1 302 Moved Temporarily
Cache-Control: max-age=0, no-cache, no-store
Connection: keep-alive
Content-Length: 0
Date: Tue, 28 May 2019 19:16:36 GMT
Expires: Tue, 28 May 2019 19:16:36 GMT
Location: http://packages.nuget.org/v1/FeedService.svc/
Pragma: no-cache
Request-Context: appId=cid-v1:7d63747b-487e-492a-872d-762362f77974
Server: Kestrel
X-Powered-By: ASP.NET
X-Response-Cache-Status: True
```

Which ultimately `302`s to `Location: http://packages.nuget.org/v1/FeedService.svc/` and is correct. Thusly, the workaround is as follows:

```fsharp
let pkg = NuGet.getLatestPackage "https://packages.nuget.org/v1/FeedService.svc/" "Bogus"
```

Works.

I propose changing `NuGet.feedUrl` to point to the correct URL without any redirects to avoid razor blade cuts like this. Please let me know and I would be more than willing to submit a PR.

Many thanks,
Brian

**Comment by matthid** [comment]
Just to evaluate the impact here: I guess putting `NuGet.feedUrl` into `NuGet.getLatestPackage` never actually worked in any version of FAKE. Therefore this is not a regression.

Regarding the link itself: I'm not actually sure about the link or what exactly the link points to. Because it doesn't look like a regular NuGet v2 or v3 feed url. It seems like we don't actually want to even make that link/field public.

What do you think?

**Comment by bchavez** [comment]
I don't know. `¯\_(ツ)_/¯`

I just needed a way to get the latest package version off NuGet proper. As far as I saw, this seemed like the most logical thing to do with the APIs I had available in F# FAKE.

I'm sure there are more ways that I'm not completely aware of. I suppose if you want to [maximize the probability for people of falling into a pit of success](https://blog.codinghorror.com/falling-into-the-pit-of-success/) it's probably a good idea to keep it simple and not rely on these redirects at "go.microsoft.com" that have completely orthogonal redirect behaviors depending if URL parameters are present or not.

At least, in the source code, it's more descriptive of what that URL points to - ie: some obscure service on NuGet; not potentially a Microsoft support article.

**Comment by matthid** [comment]
> Because it doesn't look like a regular NuGet v2 or v3 feed url.

Wow, that API is really really old. It is a Nuget 1.0 Feed: https://docs.microsoft.com/en-us/nuget/release-notes/nuget-1.1
I think we can safely remove it or mark it as internal, which I guess fixes this issue.
I could add new APIs for the default v2 and v3 gallery feeds
