### ISSUE TITLE
NullReferenceException in Fake.Sql.SqlPackage

### ISSUE THREAD

**Issue by replicaJunction** [fsharp/FAKE#2456]
### Description

When trying to follow the [documentation for publishing a SQL database](https://fake.build/sql-sqlpackage.html) in an existing FAKE build script, I receive a NullReferenceException.

### Repro steps

1. Create the following target in a build.fsx script:

```fsharp
// Define variables - a valid connection string and a valid dacpac file
let connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Integrated Security=True;Database=MyDatabase;Pooling=False"
let dacPac = "path/to/dbProject.dacpac"

Target.create "DeploySQL" (fun _ ->
    Trace.log "--- Deploying SQL database ---"

    if not (File.exists dacPac) then failwithf "DacPac file does not exist at path [%s]" dacPac

    let f (args:SqlPackage.DeployDbArgs) =
        let x =
            { args with
                    Source = dacPac
                    Destination = connectionString
                    BlockOnPossibleDataLoss = Some false
                    DropObjectsNotInSource = Some true
            }
        Trace.trace (sprintf "DeployDbArgs: %A" x)
        x

    SqlPackage.deployDb f
```

2. Run FAKE using `dotnet fake build`

### Expected behavior

One of two things:

1. The target succeeds and the database is deployed successfully
2. The target fails due to a connectivity or database error, and a meaningful error is returned

### Actual behavior

The target fails and a NullReferenceException is thrown.

Here is the full error output from FAKE, including the stack trace:

```
Script reported an error:
-> BuildFailedException: Target 'DeploySQL' failed.
   StackTrace:
        at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 991
        at Fake.Core.TargetModule.runOrDefaultWithArguments(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1177
        at <StartupCode$build_0166ACA2555EF860EB69A67081D3BCDB594A6D5E6589783878D7E85B9932C100>.$Build$fsx.main@() in C:\Users\UserName\Documents\Projects\ProjectName\build.fsx:line 251
-> One or more errors occurred. (Object reference not set to an instance of an object.)
-> NullReferenceException: Object reference not set to an instance of an object.
   StackTrace:
        at Fake.Sql.SqlPackage.formatArgument$cont@111-1(DeployDbArgs args, String additionalParameters, String variables, String argumentName, Unit unitVar) in D:\a\1\s\src\app\Fake.Sql.SqlPackage\Sql.SqlPackage.fs:line 121
        at Fake.Sql.SqlPackage.formatDacPacArguments(DeployDbArgs args, String action, String outputPath, String additionalParameters, String variables) in D:\a\1\s\src\app\Fake.Sql.SqlPackage\Sql.SqlPackage.fs:line 152
        at Fake.Sql.SqlPackage.deployDb(FSharpFunc`2 setParams) in D:\a\1\s\src\app\Fake.Sql.SqlPackage\Sql.SqlPackage.fs:line 175
        at Build.clo@188-6.Invoke(TargetParameter _arg5) in C:\Users\UserName\Documents\Projects\ProjectName\build.fsx:line 205
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 299
```

### Known workarounds

When I amended the function creating DeployDbArgs and added a value for Timeout (I used `Some 120`), the task succeeded as expected.

### Proposed solution

Based on the stack trace, I tracked down the [problematic line](https://github.com/fsharp/FAKE/blob/675ab5209c91277e5e50551ee88b8f00ececdb13/src/app/Fake.Sql.SqlPackage/Sql.SqlPackage.fs#L121):

```fsharp
| Timeout when String.isNullOrEmpty(args.Profile) && args.Timeout.IsNone -> sprintf "/p:CommandTimeout=%d" args.Timeout.Value
```

This case is only hit when args.Timeout is None, and it's immediately trying to reference args.Timeout.Value (which is None, stored as Null).

I suggest providing a default value instead.

```fsharp
// Earlier in the function
let defaultTimeout = 120

// This line
| Timeout when String.isNullOrEmpty(args.Profile) && args.Timeout.IsNone -> sprintf "/p:CommandTimeout=%d" defaultTimout
```

### Related information 

* Windows 10 1809 x64
* .NET Core 2.1

```
> dotnet fake --version
FAKE 5 - F# Make (5.19.0) (this line is written to standard error, see https://github.com/fsharp/FAKE/issues/2066)
FakePath: C:\Users\taliaj\.nuget\packages\fake-cli\5.19.0\tools\netcoreapp2.1\any\Fake.Runtime.dll
Paket.Core: 5.241.2
```

**Comment by matthid** [comment]
@kmadof Should that have been just `args.Timout.IsSome` instead?
Can someone send a PR to fix this?
