### ISSUE TITLE
Fake cache failed

### ISSUE THREAD

**Issue by mastoj** [fsharp/FAKE#2521]
### Description

I was told to report this bug in the log. The exception I got:

```
Fake cache failed, please consider reporting a bug: System.Exception: Cache is invalid as 'System.IO.MemoryMappedFiles, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' doesn't exist
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at Fake.Runtime.FakeRuntime.readFromCache@291-1.Invoke(String line) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 311
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fake.Runtime.CoreCache.getCached[a](FSharpFunc`2 getUncached, FSharpFunc`2 readFromCache, FSharpFunc`2 writeToCache, FSharpFunc`2 checkCacheUpToDate) in D:\a\1\s\src\app\Fake.Runtime\CoreCache.fs:line 33
```

### Repro steps

1. Clone https://github.com/mastoj/Felizia/tree/fake_error
2. Start the dev container in vscode (I'm doing it from WSL2)
3. Run `dotnet fake build -t run`

**Comment by matthid** [comment]
I cannot reproduce this with the given steps.

One way this could have happened is when you cleaned the NuGet packages directory but not the fake cache (but in this scenario it is by design as we don't check everything before running).

**Comment by Wallace-Kelly** [comment]
A colleague was getting this error after clearing the Nuget cache. He fixed the issue, by additionally deleting the `.fake` folder (which for him was in the same folder as the *.fsx script that was calling the Fake library.)

**Comment by ralmeidalgc** [comment]
Thanks @Wallace-Kelly it fixed
