### ISSUE TITLE
ArgumentNullException in Fake.DotNet.NuGet.NuGet.NuGet

### ISSUE THREAD

**Issue by aklefdal** [fsharp/FAKE#2530]
### Description

Creating a nuget-package using Fake.DotNet.NuGet.NuGet.NuGet throws an exception in 5.20.2

### Repro steps

```
Target.create "NugetPackAndPublish" (fun _ ->
    NuGet.NuGet.NuGet (fun p -> 
        { p with
              Project = "MyProject"
              Version = version // Version of package being sent to repository
              Authors = ["MyOrg"]
              Description = " description"
              ReleaseNotes = "fake release"
              OutputPath = artifactsDir // local folder
              WorkingDir = publishDir // publish folder under main project
              PublishUrl = publishUrl // Shared folder on Octopus server
              Publish = not BuildServer.isLocalBuild})
        (appDir @@ "MyProject.nuspec"))
```

### Expected behavior

Expect nuget-package to be created

### Actual behavior

Exception is thrown:
```
Script reported an error:
-> ArgumentNullException: Value cannot be null.
   Parameter name: oldValue
   StackTrace:
     at System.String.Replace(String oldValue, String newValue)
     at Fake.Core.TraceDataModule.replace(String oldString, String replacement, TraceData t)
     at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 731
     at Fake.Core.CoreTracing.postMessage(TraceData x) in D:\a\1\s\src\app\Fake.Core.Trace\TraceListener.fs:line 373
     at Fake.Core.Trace.closeTagUnsafeEx(TagStatus status, KnownTags tag) in D:\a\1\s\src\app\Fake.Core.Trace\Trace.fs:line 173
     at Fake.Core.Trace.traceTarget@246.Invoke(TagStatus state) in D:\a\1\s\src\app\Fake.Core.Trace\Trace.fs:line 246
     at Fake.Core.Trace.asSafeDisposable@153.System-IDisposable-Dispose() in D:\a\1\s\src\app\Fake.Core.Trace\Trace.fs:line 159
     at Fake.Core.TargetModule.runSimpleContextInternal(FSharpFunc`2 traceStart, TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 312
     at Microsoft.FSharp.Collections.ArrayModule.Fold[T,TState](FSharpFunc`2 folder, TState state, T[] array) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 899
     at Fake.Core.TargetModule.runInternal(Boolean singleTarget, Int32 parallelJobs, String targetName, FSharpList`1 args) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 921
     at Fake.Core.TargetModule.getRunFunction@1111-1.Invoke(Unit unitVar0) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1111
     at Fake.Core.TargetModule.runFunction(FSharpOption`1 targetFunction) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1117
     at Fake.Core.TargetModule.runOrDefaultWithArguments(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1177
     at <StartupCode$build_63629BF8EE80697A7F65FD9B2BC50875ACBFF7FD33E05731BF4555AABA21CB1D>.$Build$fsx.main@() in C:\s\my-project\build.fsx:line 166
```

### Known workarounds

Pin Fake.Dotnet.NuGet to version 5.20.1

### Related information 

* Operating system: Windows
* Branch
* .NET Runtime, CoreCLR or Mono Version: .NET Core 3.1
* Indications of severity: Easy workaround when you know about this, but I spent a few hours before finding it.
* Version of FAKE (4.X, 5.X): 5.20.2
* (if performance issue) Performance information, links to performance testing scripts

**Comment by aklefdal** [comment]
This is probably related to https://github.com/fsharp/FAKE/pull/2527, so maybe @zvirja should take a look.

**Comment by matthid** [comment]
always when I accept PRs without tests :D.
I guess the problem is that you have no api key set (-> null)... can you send a pr with a nullcheck there? And we probably should fail early in TraceSecret.register as well

**Comment by Robbert-Driven-It** [comment]
That just cost me an afternoon

**Comment by matthid** [comment]
Yes unfortunate, just for clarification: How do you manage the nuget api key if you apparently don't set it via fake?

**Comment by Robbert-Driven-It** [comment]
I think it's broader then that, I was only using the following bit of code

`NuGet.NuGet.NuGetPack (fun p ->
        { p with
            Version = versionNumber
            WorkingDir = "./output"
            OutputPath = packageDir
            Dependencies = [
             "Akka", akkaVersion]
         })
        "./NugetSpecs/BMS.Engine.Core.nuspec"`

And it failed all the same falling back to 5.20.1 fixed it

**Comment by aklefdal** [comment]
> How do you manage the nuget api key if you apparently don't set it via fake?

We push to a inhouse server, not to nuget, so API key is not needed.

**Comment by HL-MCS** [comment]
I confirm the bug in 5.20.2.
It occurs when creating a nuget packet after FAKE already created the .nuspec.
It has most probably to do with the lines (the parameter values being null for the default)
    TraceSecrets.register "<NuGetKey>" parameters.AccessKey
    TraceSecrets.register "<NuGetSymbolKey>" parameters.SymbolAccessKey

in the let private pack functon in NuGet.fs.

Please fix
