### ISSUE TITLE
Fake doesn't support new net5.0 patforms like net5.0-windows

### ISSUE THREAD

**Issue by mk185147** [fsharp/FAKE#2555]
### Description

When you use Paket to define build script dependencies and you restrict framework for net5.0-windows then paket won't be able to execute

### Repro steps

Create a solution that is managed by paket and fake and contains net5.0-windows project

1. Put in paket.dependencies restriction to net5.0-windows

2. Paket install

3. try build it using fake

### Expected behavior

It compiles

### Actual behavior

Error like this appears:
There was a problem while setting up the environment:
-> Error during parsing of 'C:\pathToYourFolder\paket.lock'.
-> invalid parameter 'net5.0-windows7.0' after >= or < in '== net5.0-windows7.0) (== net50)'

### Related information 

* Error occurs on Fake 5.20.4-alpha.1642
* I expect creating new version of Fake with latest Paket should fix this

**Comment by 0x53A** [comment]
same, you can workaround this by first doing a manual restore with the latest paket:

```
.\.paket\paket.exe restore
dotnet fake build
```

then fake recognizes that it can skip restore.

**Comment by mk185147** [comment]
> same, you can workaround this by...

unfortunately this isn't work-around in my case = when I use framework restriction in paket.dependencies (if I don't use the restriction then I am able to work-around issue with restore like you described). This is stack trace of the issue that I see on build machine:
```
There was a problem while setting up the environment:
-> Error during parsing of 'D:\a\1\s\paket.lock'.
   StackTrace:
        at Paket.LockFile.Parse(String lockFileName, String[] lines)
        at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
        at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
        at System.Lazy`1.CreateValue()
        at System.Lazy`1.get_Value()
        at Fake.Runtime.FakeRuntime.retrieveInfosUncached@141(String cacheDir, Lazy`1 paketDependenciesFile, VerboseLevel logLevel, GroupName groupName, FrameworkIdentifier framework, Lazy`1 lockFile, Lazy`1 cache, Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 142
        at Fake.Runtime.FakeRuntime.getKnownDependencies@337-1.Invoke(Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 337
        at Fake.Runtime.CoreCache.getCached[a](FSharpFunc`2 getUncached, FSharpFunc`2 readFromCache, FSharpFunc`2 writeToCache, FSharpFunc`2 checkCacheUpToDate) in D:\a\1\s\src\app\Fake.Runtime\CoreCache.fs:line 41
        at Fake.Runtime.FakeRuntime.getKnownDependencies@335(String cacheDir, Lazy`1 paketDependenciesFile, VerboseLevel logLevel, GroupName groupName, FrameworkIdentifier framework, FileInfo lockFilePath, String dependencyCacheHashFile, String dependencyCacheFile, Lazy`1 lockFile, Lazy`1 cache, Lazy`1 writeIntellisenseTask, FSharpFunc`2 readFromCache, FSharpFunc`2 writeToCache, Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 336
        at Fake.Runtime.FakeRuntime.knownDependencies@345.Invoke(Unit unitVar) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 345
        at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
        at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
        at System.Lazy`1.CreateValue()
        at System.Lazy`1.get_Value()
        at Fake.Runtime.FakeRuntime.paketCachingProvider@354-5.Fake-Runtime-CoreCache-ICachingProvider-TryLoadCache(FakeContext context) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 361
        at Fake.Runtime.CoreCache.prepareContext(FakeConfig config, ICachingProvider cache) in D:\a\1\s\src\app\Fake.Runtime\CoreCache.fs:line 482
        at Fake.Runtime.CoreCache.runScriptWithCacheProviderExt(FakeConfig config, ICachingProvider cache) in D:\a\1\s\src\app\Fake.Runtime\CoreCache.fs:line 508
        at Fake.Runtime.FakeRuntime.runScript(PrepareInfo preparedScript) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 605
        at Program.runOrBuild(RunArguments args) in D:\a\1\s\src\app\Fake.netcore\Program.fs:line 156
-> invalid parameter 'net5.0-windows7.0' after >= or < in '== net5.0-windows7.0) (== net50)'
   StackTrace:
        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
        at Paket.Requirements.parseOperand@829(Boolean skipSimplify, List`1 problems, String text, FSharpList`1 cur, String next)
        at Paket.Requirements.parseOperator@769(Boolean skipSimplify, List`1 problems, String text)
        at Paket.Requirements.parseRestrictionsRaw(Boolean skipSimplify, String text)
        at Paket.Requirements.parseRestrictionsSimplified@881.Invoke(String text)
        at Paket.LockFileParser.|Remote|NugetPackage|NugetDependency|SourceFile|RepositoryType|Group|InstallOption|$cont@285-3(String line, FSharpOption`1 matchValue_0, String matchValue_1, Unit unitVar)
        at Paket.LockFileParser.Parse$cont@456-2(FSharpFunc`2 removeBrackets, String line, FSharpList`1 otherGroups, ParseState currentGroup, Unit unitVar)
        at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 731
        at Paket.LockFile.Parse(String lockFileName, String[] lines)
```

**Comment by davedawkins** [comment]
Please re-open. Still an issue in 5.20.3
