### ISSUE TITLE
starting of "powershell.exe" is failed

### ISSUE THREAD

**Issue by NimaRayyan** [fsharp/FAKE#2591]
### Description

Hello, im trying to do stuff with azure like the below sample , no errors  but when build the fake i get this error
code :
module AzureCli =
    type AzureCommand =
    | DbCreate
let runCommand args =
      RawCommand("powershell.exe", args)
      |> CreateProcess.fromCommand
      |> CreateProcess.redirectOutput
      |> Proc.run

    let private parse = function
      | DbCreate -> 
          Arguments.Empty
          |> Arguments.appendRaw (sprintf "az cosmosdb create ")
 let x=
           AzureCli.dbCreate
           |> Arguments.appendOption "--name" (Some dbParams.["dbName"])
           |> Arguments.appendOption "--resource-group" (Some dbParams.["ResourceGroup"])
           |> Arguments.appendOption "--subscription" (Some dbParams.["Subscription"])

           |> AzureCli.runCommand

 "powershell.exe" "az cosmosdb create " --name fake3 --resource-group AuditLockerQA --subscription "\"Azure subscription 1\"" (In: false, Out: true, Err: true)
Script reported an error:
-> Start of process 'powershell.exe' failed.
   StackTrace:
        at Fake.Core.Process.processStarter@415.Invoke(RawCreateProcess c, Process p) in D:\a\1\s\src\app\Fake.Core.Process\Process.fs:line 427
        at Fake.Core.RawProc.start@207(FSharpFunc`2 startProcessRaw, RawCreateProcess c, ProcessStartInfo p, StreamSpecs streamSpec, Process toolProcess, CancellationTokenSource tok, FSharpRef`1 isStarted, FSharpRef`1 readOutputTask, FSharpRef`1 readErrorTask, FSharpRef`1 redirectStdInTask, Unit unitVar0) in D:\a\1\s\src\app\Fake.Core.Process\RawProc.fs:line 212
        at Fake.Core.RawProc.syncStart@268.Invoke(Unit unitVar0) in D:\a\1\s\src\app\Fake.Core.Process\RawProc.fs:line 270
     --- End of stack trace from previous location where exception was thrown ---
        at Microsoft.FSharp.Control.AsyncResult`1.Commit() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 338
        at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 870
        at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 878
        at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1142
        at Fake.Core.Proc.run[a](CreateProcess`1 c) in D:\a\1\s\src\app\Fake.Core.Process\Process.fs:line 1095
        at <StartupCode$build_AE9FAAD008273F7172F1C11996DCDE994242E128B374896B0AB1724C3B75FC6A>.$Build$fsx.main@() in C:\Users\MSI\Desktop\work\projects\AuditLocker\AuditLogManager\build.fsx:line 80
-> Win32Exception: The specified executable is not a valid application for this OS platform.
   StackTrace:
        at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
        at System.Diagnostics.Process.Start()
        at Fake.Core.Process.processStarter@415.Invoke(RawCreateProcess c, Process p) in D:\a\1\s\src\app\Fake.Core.Process\Process.fs:line 425
Performance:

### Expected behavior

powershell should be called successfully 
### Actual behavior

it return error

**Comment by NimaRayyan** [comment]
fixed by using full path of powershell
