### ISSUE TITLE
Running into PathTooLongExceptions with our project because we have node_modules.

### ISSUE THREAD

**Issue by albertjan** [fsharp/FAKE#537]
Would it be an idea to add a flag somewhere where you can say I don't care about paths that are too long when globbing?

Or maybe have a list of directories that should be ignored when globbing.

**Comment by fbeauche** [comment]
Is it possible there is a regression on this bug ? 
We have path too long exception with RestorePackage when node_modules folder is present: 
.\packages\FAKE\tools\FAKE.exe --version

FakePath: C:\dev\ppp\source\gppp\packages\FAKE\tools\FakeLib.dll
FAKE - F# Make "3.18.0"

 .\packages\FAKE\tools\FAKE.exe .\build.fsx
F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\dev\ppp\source\gppp\build.fsx]

System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern)
   at Fake.FileSystem.buildPaths@53-2.Invoke(String dir) in C:\code\fake\src\app\FakeLib\Globbing\FileSystem.fs:line 53
   at Microsoft.FSharp.Collections.IEnumerator.map@116.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@674[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Fake.FileSystem.search(String baseDir, String input) in C:\code\fake\src\app\FakeLib\Globbing\FileSystem.fs:line 78
   at Fake.FileSystem.System-Collections-Generic-IEnumerable-1-GetEnumerator@109-2.GenerateNext(IEnumerable`1& next) in C:\code\fake\src\app\FakeLib\Globbing\FileSystem.fs:line 110
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.IEnumerator.next@185[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0)
   at Microsoft.FSharp.Collections.IEnumerator.filter@180.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.IEnumerator.next@185[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0)
   at Microsoft.FSharp.Collections.IEnumerator.filter@180.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at <StartupCode$FSI_0001>.$FSI_0001_Build$fsx.main@() in C:\dev\ppp\source\gppp\build.fsx:line 23
Stopped due to error

**Comment by albertjan** [comment]
@fbeache It's not a regression. You just can't have these long paths on windows when using .net. Its a stupid restriction microsoft thought up years and years ago. The fix @forki added was just to prevent fake to go look for nuget.exe by specifying it yourself.

**Comment by fbeauche** [comment]
Its failing when looking for the packages.config: 

let nugetPath = EnvironmentHelper.environVarOrDefault "nugetPath" @"C:\tools\nuget\nuget.exe"
Target "RestorePackages" (fun _ ->
    !! "*/**/packages.config"
    |> Seq.iter (RestorePackage ( fun p -> {p with ToolPath = nugetPath }))
)

**Comment by colinbull** [comment]
I started working on a fix for this mentioned above, but there is is lots of ins-and-outs when dealing with a long paths. It is probably just best avoided - I couldn't really get it working smoothly which is why I dropped it.
