### ISSUE TITLE
Weird error after switching to paket

### ISSUE THREAD

**Issue by albertjan** [fsharp/FAKE#754]
I'm getting this unhandled exception from the `FSharp.Core` lib after a `Shell.Exec` in my buildscript here: https://github.com/fsprojects/oxen/blob/switch-to-paket/build.fsx#L148. But the weirdest thing is the only thing that has changes afaics is that I switched from nuget to paket. In the master branch it does work.

```
Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1224-1.Invoke(Exception e)
   at <StartupCode$FSharp-Core>.$Control.loop@425-40(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@510-1.Invoke(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by forki** [comment]
did you change the referenced FSharp.Core?

**Comment by albertjan** [comment]
Funny enough of all the lines changed in the diff the ref to f# core isn't

here:
https://github.com/fsprojects/oxen/commit/2445bf90659da9b1c02b83da0ac026340336e805#diff-d51856c9d7c0ae270dc9e8b1878c19eeL91

and here:
https://github.com/fsprojects/oxen/commit/2445bf90659da9b1c02b83da0ac026340336e805#diff-3abb3346dc00cb7e0a1c18c2fa251cccL83

**Comment by forki** [comment]
Are you sure the exe is there? After rereading the exception it's just complaining about the missing file

**Comment by albertjan** [comment]
The exe is there and is started. And also that wouldn't result in an unhandled error in FAKE.exe fake would just tell me it can't find the exe right?

**Comment by forki** [comment]
Probably. But some file is missing or in different place now.

**Comment by albertjan** [comment]
```
npm found here: C:\Program Files\nodejs\npm

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1224-1.Invoke(Exception e)
   at <StartupCode$FSharp-Core>.$Control.loop@425-40(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at Microsoft.FSharp.Control.TrampolineHolder.Protect(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@510-1.Invoke(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object
state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, B
oolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
npm WARN package.json oxen.Tests@0.0.1 No repository field.
npm WARN package.json oxen.Tests@0.0.1 No README data
Finished Target: RunNpmInstall
Starting Target: StartTestControlQueue (==> RunNpmInstall)
```
the npm warn lines are from the shell.exec

**Comment by albertjan** [comment]
And when I comment out the shell.exec it fails before the next shell.exec.

**Comment by albertjan** [comment]
https://github.com/fsprojects/oxen/commit/2445bf90659da9b1c02b83da0ac026340336e805#diff-3abb3346dc00cb7e0a1c18c2fa251cccL83 The only files that have been deleted are nugets package.config

**Comment by albertjan** [comment]
I'm a moron and you're right :smile: there was a dependency missing in my paket.dependency file. And it was failing somewhere else because I started it async.
