### ISSUE TITLE
Fake.Deploy needs fsi?

### ISSUE THREAD

**Issue by ashic** [fsharp/FAKE#760]
It seems I can run fake.exe build.fsx on a system that doesn't have fsi, but if I try:

```
fake.deploy.exe /deploy . path/to/somepkg.0.0.1.nupkg
```

then I get the following error:

```
Deleting contents of .\deployments/MyWindowsService\active
Exception Message:Start of process fsi.exe failed. The system cannot find the file specified
**************************************************
Type: System.Exception
TargetSite: Microsoft.FSharp.Core.Unit Invoke(System.String)
Source: FakeLib
HResult: -2146233088

StackTrace
**************************************************

   at Fake.ProcessHelper.ExecProcessWithLambdas@76-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.ProcessHelper.ExecProcessRedirected(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 118
   at Fake.DeploymentHelper.doDeployment(String scriptFileName, String[] scriptArgs) in C:\code\fake\src\app\Fake.Deploy\DeploymentHelper.fs:line 77
Deployment of C:\vagrant\MyWindowsService.0.0.4.nupkg to local failed
System.Exception: Start of process fsi.exe failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@76-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 76
   at Fake.ProcessHelper.ExecProcessRedirected(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 118
   at Fake.DeploymentHelper.doDeployment(String scriptFileName, String[] scriptArgs) in C:\code\fake\src\app\Fake.Deploy\DeploymentHelper.fs:line 77

Deploy messages
{

}
```

Does that mean Fake.Deploy.exe doesn't use the same stuff as Fake? Is this by design (i.e. we need fsi to use Fake.Deploy) or a bug?

**Comment by forki** [comment]
Yes it's true FAKE.deploy needs the fsi. We used to host the FCS but we had issues with getting to a fresh state after running a deploy.

**Comment by ashic** [comment]
Makes sense. Thanks for confirming.
