### ISSUE TITLE
NUnitParallel output is not displayed in console

### ISSUE THREAD

**Issue by khanage** [fsharp/FAKE#828]
If I run NUnitParallel with failing tests, I don't get any output from them, and any error is just a general exception that looks like:

```
Fake.UnitTestCommon+FailedTestsException: NUnitParallel test runs failed (1 of 1 assemblies are failed).
   at Fake.NUnitParallel.fail@100[a](FSharpList`1 testRunResults, AggFailedResult aggResult, FSharpList`1 matchValue, Unit unitVar0) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Parallel.fs:line 102
   at Fake.NUnitParallel.NUnitParallel(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Parallel.fs:line 112
   at FSI_0001.Build.clo@82-7.Invoke(Unit _arg5) in C:\Users\khan\Dropbox\dev\Csn.Storage\leeloo\build.fsx:line 85
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411
```

If I just use NUnit I get a reasonable error message, as well as output for which test fixtures I'm running.

I'm using FAKE 3.35.1.

**Comment by matthid** [comment]
Closing old issue, I doubt that a lot of people are still using NUnit2.
