### ISSUE TITLE
XUnit tests don't run after updating XUnit assemblies

### ISSUE THREAD

**Issue by gsscoder** [fsharp/FAKE#833]
I'm recently switched to use **FAKE** and I'm very pleased with it.

When I've upgraded XUnit libraries for my test project, I was not able to run tests anymore. Test assembly is dependent on **.NET 4.5** while tested project (a library itself) set to **.NET 4.0**. [Project](https://github.com/gsscoder/commandline) is open source, so if you want you can check everything.

I've the same issue also on OSX/Mono, but I'll post here what shows on Windows/PowerShell:
```PowerShell
Finished Target: BuildTest
Starting Target: Test (==> BuildTest)
Running Tests...
P:\CommandLine\packages\xunit.runners.1.9.1\tools\xunit.console.clr4.exe "P:\CommandLine\build\test\CommandLine.Tests.dl
l"
xUnit.net console test runner (64-bit .NET 4.0.30319.18408)
Copyright (C) 2007-11 Microsoft Corporation.

error: Could not find file: P:\CommandLine\build\test\xunit.dll
Running build failed.
Error:
System.Exception: xUnit failed for the following assemblies: P:\CommandLine\build\test\CommandLine.Tests.dll
   at Microsoft.FSharp.Core.Operators.FailWith[T](String message)
   at Fake.XUnitHelper.xUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\
XUnit\XUnitHelper.fs:line 143
   at FSI_0001.Build.clo@35-5.Invoke(Unit _arg5) in P:\CommandLine\build.fsx:line 37
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 41
1

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target      Duration
------      --------
Clean       00:00:00.1360413
BuildLib    00:00:01.6065345
BuildTest   00:00:03.1894355
Total:      00:00:08.8185649
Status:     Failure
---------------------------------------------------------------------
  1) System.Exception: xUnit failed for the following assemblies: P:\CommandLine\build\test\CommandLine.Tests.dll
   at Microsoft.FSharp.Core.Operators.FailWith[T](String message)
   at Fake.XUnitHelper.xUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\
XUnit\XUnitHelper.fs:line 143
   at FSI_0001.Build.clo@35-5.Invoke(Unit _arg5) in P:\CommandLine\build.fsx:line 37
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 41
1
---------------------------------------------------------------------
```

This is the task snippet of [build.fsx](https://github.com/gsscoder/commandline/blob/master/build.fsx):
```F#
Target "Test" (fun _ ->
    trace "Running Tests..."
    !! (testDir + @"\CommandLine.Tests.dll") 
      |> xUnit (fun p -> {p with OutputDir = testDir})
)
```

Also compiling the library DLL to .NET 4.5 doesn't solve the problem.

**Comment by inosik** [comment]
Since you are using xUnit **v2** now, you have to use the appropriate [runner](https://www.nuget.org/packages/xunit.runner.console) and [helper function](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/UnitTest/XUnit/XUnit2.fs#L200).

BTW, xUnit 2 seems to not work on Mono yet.

**Comment by gsscoder** [comment]
Thanks for the help, using right task and console runner solved the problem.

You're right, stable runners doesn't work on Mono (I've not tried with pre-release). Anyway this doesn't happen due to **FAKE**, so I think the issue can be closed.
