### ISSUE TITLE
RunTargetOrDefault's default Target is not honored and "test" is used instead

### ISSUE THREAD

**Issue by KevM** [fsharp/FAKE#842]
## FAKE 3.35.4.0

Using this script.

```fs
// include Fake lib
#r "packages/FAKE/tools/FakeLib.dll"
open Fake

Target "Default" (fun _ -> 
  trace "Hello World"
)

// start build
RunTargetOrDefault "Default"
```

Results in a failure. The default target is not used. Instead the target `test` is used. Interestingly if the script has a `Test` target it is not invoked. If you do give FAKE a target to run it runs it.

```
> packages\FAKE\tools\Fake.exe test.fsx
Building project with version: LocalBuild
The following targets are available:
   Default
Target ""test"" is not defined. Existing targets:
  - Default

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
No target was successfully completed
---------------------------------------------------------------------

F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\projects\name\test.fsx]

System.Exception: Target ""test"" is not defined.
   at Fake.TargetHelper.getTarget@72-2.Invoke(String message) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 72
   at Fake.TargetHelper.runTarget@431(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 433
   at Fake.TargetHelper.run$cont@429(String targetName, Unit unitVar) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 463
   at Fake.TargetHelper.run(String targetName) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 429
   at Fake.AdditionalSyntax.RunTargetOrDefault(String defaultTarget) in C:\code\fake\src\app\FakeLib\AdditionalSyntax.fs:line 29
   at <StartupCode$FSI_0001>.$FSI_0001_Test$fsx.main@() in C:\projects\name\test.fsx:line 10
Stopped due to error
```

**Comment by KevM** [comment]
I cannot reproduce this in FAKE 4.0.3
