### ISSUE TITLE
Fake.Deploy fails to run install script

### ISSUE THREAD

**Issue by Mharlin** [fsharp/FAKE#909]
I've updated Fake.Deploy 4.1.3 on the remote server. When deploying I get the following error message:
{
  "ClassName": "System.Exception",
  "Message": "Deployment script didn't run successfully",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": null,
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146233088,
  "Source": null,
  "WatsonBuckets": null
}

Deploy messages
{
  2015-08-14 01::10:03.695
  2015-08-14 01::10:03.695 Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  2015-08-14 01::10:03.695    at Microsoft.FSharp.Compiler.Interactive.Shell.MainMain(String[] argv)
  2015-08-14 01::10:03.695    at Microsoft.FSharp.Compiler.Interactive.Main.FsiMain(String[] argv)
}

   at Fake.FakeDeployAgentHelper.DeployPackageWithArgs@194-4.Invoke(String message) in C:\code\fake\src\app\Fake.Deploy.Lib\FakeDeployAgentHelper.fs:line 194
   at Fake.FakeDeployAgentHelper.DeployPackageWithArgs(String url, String packageFileName, String[] args) in C:\code\fake\src\app\Fake.Deploy.Lib\FakeDeployAgentHelper.fs:line 194
   at FSI_0001.Build.clo@68-6.Invoke(Unit _arg5) in C:\Projekt\Rehab\LogParsers\build.fsx:line 70
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 411

I haven't changed anything in my deployment script, only updated the Fake.Deploy on the remote server.

**Comment by Mharlin** [comment]
The ugly solution was to go into the fsi.exe.config and add this assembly redirect:
`<bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0"/>`

I hope this helps to solve this the proper way as well.

**Comment by matthid** [comment]
Closing old issue, not sure if anyone still uses Fake.Deploy.
